//-----------------------------------------------------------------------
// <copyright file="AssemblyInfo.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation.
// </copyright>
//-----------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("EsentInterop")]
[assembly: AssemblyDescription("Managed interop code for esent.dll")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("EsentInterop")]
[assembly: AssemblyCopyright("Copyright ©  Microsoft")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

[assembly: CLSCompliant(true)]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.6.0.0")]
[assembly: AssemblyFileVersion("1.6.0.0")]

[assembly: InternalsVisibleTo("InteropApiTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001005d9fe08a905f48ce8e805322b0560c551c152b1b8d5fa164f75b4256512481f09f0dc39b70486910ce9e449f11facb48a1578e31d280a9a01d4074b5ba56d6fcf5037d8901b9b213305f15e1a1df7417de0048af73f7b1679c4583e6c07a387aad815b2fa1a39613cb722b0d9e3054c9414da497729c5534fe229b72c751a694")]
[assembly: InternalsVisibleTo("Pixie, PublicKey=00240000048000009400000006020000002400005253413100040000010001005d9fe08a905f48ce8e805322b0560c551c152b1b8d5fa164f75b4256512481f09f0dc39b70486910ce9e449f11facb48a1578e31d280a9a01d4074b5ba56d6fcf5037d8901b9b213305f15e1a1df7417de0048af73f7b1679c4583e6c07a387aad815b2fa1a39613cb722b0d9e3054c9414da497729c5534fe229b72c751a694")]
[assembly: InternalsVisibleTo("PixieTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001005d9fe08a905f48ce8e805322b0560c551c152b1b8d5fa164f75b4256512481f09f0dc39b70486910ce9e449f11facb48a1578e31d280a9a01d4074b5ba56d6fcf5037d8901b9b213305f15e1a1df7417de0048af73f7b1679c4583e6c07a387aad815b2fa1a39613cb722b0d9e3054c9414da497729c5534fe229b72c751a694")]

// This assembly is generated by Rhino.Mocks
//[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]