import { SampleScript, SamplesTab } from "components/common/sampleQueries/partials/sampleQueriesTypes";
import { createSampleScriptsTab } from "components/common/sampleQueries/partials/samplesTabFactories";

// Placeholder samples migrated from the previous syntax-help modals.

const contextScriptSamples: SampleScript[] = [
    {
        title: "Generate context objects",
        description: "Iterate over the source document and emit one context object per item.",
        language: "javascript",
        script: `for(const comment of this.Comments)  // 'this' is the source document
{
    // Call 'ai.genContext' to generate a context object for each comment.
    // The custom object passed to this method defines the structure of the context object.
    ai.genContext({
        Text: \`Blog post topic: \${this.Topic}. Comment: \${comment.Text}\`,
        AuthorName: comment.Author,
        CommentId: comment.Id
    });
}`,
    },
    {
        title: "With attachments",
        description: "Attach document attachments (images, text files) to the generated context objects.",
        language: "javascript",
        script: `for(const comment of this.Comments)
{
    ai.genContext({ Id: comment.Id })
        .withPng(loadAttachment("heart.png"))
        .withText(loadAttachment("transactions.csv"))
        .withText(loadAttachment("text.txt"));
}`,
    },
];

const promptSamples: SampleScript[] = [
    {
        title: "Spam detection prompt",
        description: "",
        language: "plaintext",
        whiteSpace: "pre-wrap",
        script: "Check if the following blog post comment is spam or not. A spam comment typically includes irrelevant or promotional content, excessive links, misleading information, or is written with the intent to manipulate search rankings or advertise products/services. Consider the language, intent, and relevance of the comment to the blog post topic.",
    },
];

const sampleObjectSamples: SampleScript[] = [
    {
        title: "Sample response object",
        description: "The shape of the object the model should return.",
        language: "json",
        script: `{
    "IsCommentSpam": true,
    "Reason": "Concise reason for why this comment was marked as spam or ham"
}`,
    },
];

const updateScriptSamples: SampleScript[] = [
    {
        title: "Update the source document",
        description: "React to the model output: remove spam comments and archive them in a separate collection.",
        language: "javascript",
        script: `// $input - the model input (generated by ai.genContext())
// $output - the model output
// this - the source document

const idx = this.Comments.findIndex(comment => comment.Id == $input.CommentId);
if ($output.IsCommentSpam) {
    // Update the source document:
    this.Comments.splice(idx, 1); // remove comment
    // Can create new documents:
    const newDocument = { "comment": $input.Text, "@metadata": { "@collection": "spamComments"} };
    put(id(this) +"/spam/", newDocument);
}`,
    },
];

const jsonSchemaSamples: SampleScript[] = [
    {
        title: "Sample JSON schema",
        description: "The schema that will be sent to the model, describing the expected response object.",
        language: "json",
        script: `{
  "name": "some-name",
  "strict": true,
  "schema": {
    "type": "object",
    "properties": {
      "IsCommentSpam": {
        "type": "boolean"
      },
      "Reason": {
        "type": "string",
        "description": "Concise reason for why this comment was marked as spam or ham"
      }
    },
    "required": [
      "IsCommentSpam",
      "Reason"
    ],
    "additionalProperties": false
  }
}`,
    },
];

const queryToolParametersSamples: SampleScript[] = [
    {
        title: "Query parameters",
        description: "Instruct the LLM what value to supply for each query parameter.",
        language: "json",
        script: `{
    "country": "Provide the country to which the order was shipped.",
    "company": "Provide the company that placed this order."
}`,
    },
    {
        title: "Vector search parameters",
        description: "Parameters for a semantic search query.",
        language: "json",
        script: `{
    "searchTerm": "Provide the name of a product to search for similar items.",
    "similarityLevel": "Provide the similarity level to apply in the search."
}`,
    },
    {
        title: "No parameters",
        description: "Use an empty object when the query takes no parameters.",
        language: "json",
        script: `{}`,
    },
];

const queryToolParametersSchemaSamples: SampleScript[] = [
    {
        title: "Parameters JSON schema",
        description: "The schema generated from the sample parameters object.",
        language: "json",
        script: `{
    "type": "object",
    "properties": {
        "country": {
            "type": "string",
            "description": "Provide the country to which the order was shipped."
        },
        "company": {
            "type": "string",
            "description": "Provide the company that placed this order."
        }
    },
    "required": [
        "country",
        "company"
    ],
    "additionalProperties": false
}`,
    },
];

export const contextScriptSamplesTabs: SamplesTab[] = [createSampleScriptsTab(contextScriptSamples)];
export const promptSamplesTabs: SamplesTab[] = [createSampleScriptsTab(promptSamples)];
export const sampleObjectSamplesTabs: SamplesTab[] = [createSampleScriptsTab(sampleObjectSamples)];
export const jsonSchemaSamplesTabs: SamplesTab[] = [createSampleScriptsTab(jsonSchemaSamples)];
export const updateScriptSamplesTabs: SamplesTab[] = [createSampleScriptsTab(updateScriptSamples)];
export const queryToolParametersSamplesTabs: SamplesTab[] = [createSampleScriptsTab(queryToolParametersSamples)];
export const queryToolParametersSchemaSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(queryToolParametersSchemaSamples),
];
