using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Features.Authentication;
using Raven.Client;
using Raven.Client.Documents.Commands;
using Raven.Client.Exceptions.Security;
using Raven.Client.Http;
using Raven.Client.ServerWide;
using Raven.Client.ServerWide.Operations.Certificates;
using Raven.Client.Util;
using Raven.Server.Commercial;
using Raven.Server.Commercial.LetsEncrypt;
using Raven.Server.Config;
using Raven.Server.Documents.Operations;
using Raven.Server.Extensions;
using Raven.Server.Json;
using Raven.Server.Logging;
using Raven.Server.Routing;
using Raven.Server.ServerWide;
using Raven.Server.ServerWide.Commands;
using Raven.Server.ServerWide.Context;
using Raven.Server.Utils;
using Sparrow.Json;
using Sparrow.Logging;
using Sparrow.Platform;
using Sparrow.Server.Logging;
using Sparrow.Server.Platform.Posix;
using Sparrow.Utils;

namespace Raven.Server.Web.Authentication
{
    public sealed class AdminCertificatesHandler : ServerRequestHandler
    {
        private static readonly RavenLogger Logger = RavenLogManager.Instance.GetLoggerForServer<AdminCertificatesHandler>();

        private static readonly RavenAuditLogger AuditLogger = RavenLogManager.Instance.GetAuditLoggerForServer();


        public const string HasTwoFactorFieldName = "HasTwoFactor";
        public const string TwoFactorExpirationDate = "TwoFactorExpirationDate";

        private const string SsoServerCertificatePath = "/api/certificate";
        private const long MaxFetchedCertBytes = 1 * 1024 * 1024;
        private static readonly TimeSpan SsoCertFetchTimeout = TimeSpan.FromSeconds(10);

        private static readonly RavenHttpClient SsoCertFetchClient = new RavenHttpClient(new HttpClientHandler { AllowAutoRedirect = false })
        {
            MaxResponseContentBufferSize = MaxFetchedCertBytes
        };

        [RavenAction("/admin/certificates/2fa/generate", "GET", AuthorizationStatus.Operator)]
        public async Task GenerateSecret()
        {
            await ServerStore.EnsureNotPassiveAsync();

            var secret = TwoFactorAuthentication.GenerateSecret();

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (context.OpenReadTransaction())
            await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
            {
                writer.WriteStartObject();
                writer.WritePropertyName("Secret");
                writer.WriteString(secret);
                writer.WriteEndObject();
            }
        }

        [RavenAction("/admin/certificates", "POST", AuthorizationStatus.Operator, DisableOnCpuCreditsExhaustion = true)]
        public async Task Generate()
        {
            // one of the first admin action is to create a certificate, so let
            // us also use that to indicate that we are the seed node
            await ServerStore.EnsureNotPassiveAsync();
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (ctx.OpenReadTransaction())
            {
                var operationId = GetLongQueryString("operationId", false);
                if (operationId.HasValue == false)
                    operationId = ServerStore.Operations.GetNextOperationId();

                var stream = TryGetRequestFromStream("Options") ?? RequestBodyStream();

                var certificateJson = await ctx.ReadForDiskAsync(stream, "certificate-generation");

                certificateJson.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out string twoFactorAuthenticationKey);

                var certificate = JsonDeserializationServer.CertificateDefinition(certificateJson);

                if (certificate.Usage == CertificateUsage.SsoServer)
                    throw new InvalidOperationException("SSO server certificates cannot be generated by RavenDB. Upload an externally generated SSO server certificate using PUT /admin/certificates instead.");

                if (certificate.SecurityClearance == SecurityClearance.ClusterAdmin && IsClusterAdmin() == false)
                {
                    var clientCert = (HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection)?.Certificate;
                    var clientCertDef = ReadCertificateFromCluster(ctx, clientCert?.Thumbprint);
                    throw new InvalidOperationException($"Cannot generate the client certificate '{certificate.Name}' with 'Cluster Admin' security clearance because the current client certificate being used has a lower clearance: {clientCertDef.SecurityClearance}");
                }

                if (RavenLogManager.Instance.IsAuditEnabled)
                {
                    var permissions = FormatPermissions(certificate);

                    LogAuditForServer("GENERATE",
                        $"Certificate {certificate?.Name}. Security Clearance: {certificate?.SecurityClearance}. Permissions: {permissions}. TwoFactor: {string.IsNullOrEmpty(twoFactorAuthenticationKey) == false}");
                }

                byte[] certs = null;
                await ServerStore.Operations.AddLocalOperation(
                        operationId.Value,
                        OperationType.CertificateGeneration,
                        "Generate certificate: " + certificate.Name,
                        detailedDescription: null,
                        async onProgress =>
                        {
                            certs = await GenerateCertificateInternal(certificate, ServerStore, twoFactorAuthenticationKey, GetRaftRequestIdFromQuery());

                            return ClientCertificateGenerationResult.Instance;
                        });

                var contentDisposition = "attachment; filename=" + Uri.EscapeDataString(certificate.Name) + ".zip";
                HttpContext.Response.Headers[Constants.Headers.ContentDisposition] = contentDisposition;
                HttpContext.Response.ContentType = "application/octet-stream";

                await HttpContext.Response.Body.WriteAsync(certs, 0, certs.Length);
            }
        }

        public static async Task<byte[]> GenerateCertificateInternal(CertificateDefinition certificate, ServerStore serverStore, string twoFactorAuthenticationKey, string raftRequestId)
        {
            ValidateCertificateDefinition(certificate, serverStore);

            if (serverStore.Server.Certificate?.ServerCertificate == null)
            {
                var keys = new[]
                {
                    RavenConfiguration.GetKey(x => x.Security.CertificatePath),
                    RavenConfiguration.GetKey(x => x.Security.CertificateLoadExec)
                };

                throw new InvalidOperationException($"Cannot generate the client certificate '{certificate.Name}' because the server certificate is not loaded. " +
                                                    $"You can supply a server certificate by using the following configuration keys: {string.Join(", ", keys)}" +
                                                    "For a more detailed explanation please read about authentication and certificates in the RavenDB documentation.");
            }

            // this creates a client certificate which is signed by the current server certificate
            var selfSignedCertificate = CertificateUtils.CreateSelfSignedClientCertificate(certificate.Name, serverStore.Server.Certificate.ServerCertificate,
                serverStore.Server.Certificate.PrivateKey, out _,
                certificate.NotAfter ?? DateTime.UtcNow.Date.AddYears(5));

            var newCertDef = new CertificateDefinition
            {
                Name = certificate.Name,
                // this does not include the private key, that is only for the client
                Certificate = Convert.ToBase64String(selfSignedCertificate.Export(X509ContentType.Cert)),
                Permissions = certificate.Permissions,
                SecurityClearance = certificate.SecurityClearance,
                Thumbprint = selfSignedCertificate.Thumbprint,
                PublicKeyPinningHash = selfSignedCertificate.GetPublicKeyPinningHash(),
                NotAfter = selfSignedCertificate.NotAfter,
                NotBefore = selfSignedCertificate.NotBefore,
                Usage = CertificateUsage.Client
            };

            var res = await serverStore.PutValueInClusterAsync(new PutCertificateCommand(selfSignedCertificate.Thumbprint, newCertDef, raftRequestId)
            {
                TwoFactorAuthenticationKey = twoFactorAuthenticationKey
            });
            await serverStore.Cluster.WaitForIndexNotification(res.Index);

            var ms = new MemoryStream();
            using (var archive = new ZipArchive(ms, ZipArchiveMode.Create, true))
            {
                var certBytes = selfSignedCertificate.Export(X509ContentType.Pfx, certificate.Password);

                var entry = archive.CreateEntry(certificate.Name + ".pfx");

                // Structure of the external attributes field: https://unix.stackexchange.com/questions/14705/the-zip-formats-external-file-attribute/14727#14727
                // The permissions go into the most significant 16 bits of an int
                entry.ExternalAttributes = ((int)(FilePermissions.S_IRUSR | FilePermissions.S_IWUSR)) << 16;

                await using (var s = entry.Open())
                    await s.WriteAsync(certBytes, 0, certBytes.Length);

                await LetsEncryptCertificateUtil.WriteCertificateAsPemToZipArchiveAsync(certificate.Name, certBytes, certificate.Password, archive);
            }

            return ms.ToArray();
        }


        [RavenAction("/admin/certificates", "PUT", AuthorizationStatus.Operator)]
        public async Task Put()
        {
            // one of the first admin action is to create a certificate, so let
            // us also use that to indicate that we are the seed node

            await ServerStore.EnsureNotPassiveAsync();
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (var certificateJson = await ctx.ReadForDiskAsync(RequestBodyStream(), "put-certificate"))
            {
                var certificate = JsonDeserializationServer.CertificateDefinition(certificateJson);

                certificateJson.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out string twoFactorAuthenticationKey);

                ValidateCertificateDefinition(certificate, ServerStore);

                if (certificate.Usage == CertificateUsage.SsoServer)
                {
                    ServerStore.LicenseManager.AssertCanUseSso();
                    if (IsClusterAdmin() == false)
                        throw new InvalidOperationException($"Cannot register SSO server certificate '{certificate.Name}'. Only Cluster Admins can register SSO server certificates.");
                }

                using (ctx.OpenReadTransaction())
                {
                    var clientCert = (HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection)?.Certificate;
                    var clientCertDef = ReadCertificateFromCluster(ctx, clientCert?.Thumbprint);

                    if ((certificate.SecurityClearance == SecurityClearance.ClusterAdmin || certificate.SecurityClearance == SecurityClearance.ClusterNode) && IsClusterAdmin() == false)
                        throw new InvalidOperationException($"Cannot save the certificate '{certificate.Name}' with '{certificate.SecurityClearance}' security clearance because the current client certificate being used has a lower clearance: {clientCertDef.SecurityClearance}");

                    if (string.IsNullOrWhiteSpace(certificate.Certificate))
                        throw new ArgumentException($"{nameof(certificate.Certificate)} is a mandatory property when saving an existing certificate");
                }

                byte[] certBytes;
                try
                {
                    certBytes = Convert.FromBase64String(certificate.Certificate);
                }
                catch (Exception e)
                {
                    throw new ArgumentException($"Unable to parse the {nameof(certificate.Certificate)} property, expected a Base64 value", e);
                }

                try
                {
                    var password = string.IsNullOrEmpty(certificate.Password) ? null : certificate.Password;
                    using var certificate2 = CertificateLoaderUtil.CreateCertificate(certBytes, password);
                }
                catch (Exception e)
                {
                    throw new ArgumentException("Unable to load the provided certificate.", e);
                }

                if (AuditLogger.IsAuditEnabled)
                {
                    var permissions = FormatPermissions(certificate);
                    LogAuditForServer("ADD",
                        $"New certificate {certificate?.Name} ['{certificate?.Thumbprint}']. Security Clearance: {certificate?.SecurityClearance}. Permissions:{permissions}. TwoFactor: {string.IsNullOrEmpty(twoFactorAuthenticationKey) == false}");
                }

                try
                {
                    await PutCertificateCollectionInCluster(certificate, certBytes, certificate.Password, ServerStore, ctx, twoFactorAuthenticationKey, GetRaftRequestIdFromQuery());
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException($"Failed to put certificate {certificate.Name} in the cluster.", e);
                }

                NoContentStatus(HttpStatusCode.Created);
            }
        }

        [RavenAction("/admin/certificates/sso/user", "PUT", AuthorizationStatus.Operator)]
        public async Task PutSsoUser()
        {
            await ServerStore.EnsureNotPassiveAsync();

            ServerStore.LicenseManager.AssertCanUseSso();

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (var certificateJson = await ctx.ReadForDiskAsync(RequestBodyStream(), "put-sso-user-certificate"))
            {
                var certificateDefinition = JsonDeserializationServer.CertificateDefinition(certificateJson);

                if (string.IsNullOrWhiteSpace(certificateDefinition.Name))
                    throw new ArgumentException($"{nameof(certificateDefinition.Name)} is a required field for SSO user entries.");

                if (certificateDefinition.SsoIdentifiers == null || certificateDefinition.SsoIdentifiers.Count == 0)
                    throw new ArgumentException("At least one SSO identifier is required.");

                if (certificateDefinition.AllowAnySsoServer == false &&
                    (certificateDefinition.SsoServerPublicKeyPinningHashes == null || certificateDefinition.SsoServerPublicKeyPinningHashes.Count == 0))
                    throw new ArgumentException("Either set AllowAnySsoServer = true or provide at least one SSO server public key pinning hash.");

                // Enforce the same clearance-escalation rule as PUT /admin/certificates: only Cluster Admins may
                // grant ClusterAdmin/ClusterNode clearance
                if ((certificateDefinition.SecurityClearance == SecurityClearance.ClusterAdmin || certificateDefinition.SecurityClearance == SecurityClearance.ClusterNode) && IsClusterAdmin() == false)
                    throw new InvalidOperationException($"Cannot save the SSO user entry '{certificateDefinition.Name}' with '{certificateDefinition.SecurityClearance}' security clearance because the current client certificate being used has a lower clearance.");

                using (ctx.OpenReadTransaction())
                {
                    // Validate that every provided pinning hash matches a registered SSO server cert
                    if (certificateDefinition.AllowAnySsoServer == false)
                    {
                        var allSsoHashes = new HashSet<string>(
                            ServerStore.Cluster.GetSsoServerCertificates(ctx).Select(c => c.PublicKeyPinningHash),
                            StringComparer.Ordinal);

                        foreach (var hash in certificateDefinition.SsoServerPublicKeyPinningHashes)
                        {
                            if (allSsoHashes.Contains(hash) == false)
                                throw new InvalidOperationException(
                                    $"No SSO server certificate found with public key pinning hash '{hash}'. " +
                                    "Register the SSO server certificate first using PUT /admin/certificates with Usage=SsoServer.");
                        }
                    }

                    foreach (var id in certificateDefinition.SsoIdentifiers)
                    {
                        var payload = new SsoExtensionPayload(id.Identifier, id.Provider, id.Domain);
                        var existing = ServerStore.Cluster.GetSsoClientCertificateByIdentity(ctx, payload);
                        if (existing != null)
                        {
                            throw new InvalidOperationException(
                                $"An SSO user entry with identity '{payload.GetDisplayIdentity()}' already exists " +
                                $"(name: '{existing.Name}'). Edit the existing entry instead of creating a new one.");
                        }
                    }
                }

                certificateDefinition.Usage = CertificateUsage.SsoClient;
                // Generate synthetic keys so the entry can be stored in the cert table keyed by thumbprint
                var syntheticKey = Guid.NewGuid().ToString("N");
                certificateDefinition.Thumbprint = syntheticKey;
                certificateDefinition.PublicKeyPinningHash = Guid.NewGuid().ToString();

                if (AuditLogger.IsAuditEnabled)
                {
                    var permissions = FormatPermissions(certificateDefinition);
                    var serverHashes = certificateDefinition.AllowAnySsoServer
                        ? "any"
                        : string.Join(", ", certificateDefinition.SsoServerPublicKeyPinningHashes.Select(h => $"'{h}'"));
                    var identifiers = string.Join(", ", certificateDefinition.SsoIdentifiers.Select(id =>
                        new SsoExtensionPayload(id.Identifier, id.Provider, id.Domain).GetDisplayIdentity()));
                    LogAuditForServer("ADD SSO USER",
                        $"SSO user entry '{certificateDefinition.Name}', Identifiers: [{identifiers}], SsoServerHashes: [{serverHashes}], AllowAnySsoServer: {certificateDefinition.AllowAnySsoServer}. " +
                        $"Security Clearance: {certificateDefinition.SecurityClearance}. Permissions:{permissions}");
                }

                var putCertificateCommand = new PutCertificateCommand(certificateDefinition.Thumbprint, certificateDefinition, GetRaftRequestIdFromQuery());
                await ServerStore.SendToLeaderAsync(putCertificateCommand);

                HttpContext.Response.StatusCode = (int)HttpStatusCode.Created;
                await using (var writer = new AsyncBlittableJsonTextWriter(ctx, ResponseBodyStream()))
                {
                    writer.WriteStartObject();
                    writer.WritePropertyName(nameof(CertificateDefinition.Thumbprint));
                    writer.WriteString(certificateDefinition.Thumbprint);
                    writer.WriteEndObject();
                }
            }
        }

        [RavenAction("/admin/certificates/sso/server/fetch", "GET", AuthorizationStatus.ClusterAdmin)]
        public async Task FetchSsoServerCertificateFromUrl()
        {
            ServerStore.LicenseManager.AssertCanUseSso();

            var url = GetStringQueryString("url");
            if (string.IsNullOrWhiteSpace(url))
                throw new ArgumentException("Query parameter 'url' is required.");

            if (Uri.TryCreate(url, UriKind.Absolute, out Uri baseUri) == false ||
                (baseUri.Scheme != Uri.UriSchemeHttps && baseUri.Scheme != Uri.UriSchemeHttp))
                throw new ArgumentException("The URL must be an absolute http or https URL.");

            Uri fetchUri = new UriBuilder(baseUri.Scheme, baseUri.Host, baseUri.Port)
            {
                Path = SsoServerCertificatePath
            }.Uri;

            using CancellationTokenSource cts = CancellationTokenSource.CreateLinkedTokenSource(ServerStore.ServerShutdown);
            cts.CancelAfter(SsoCertFetchTimeout);

            byte[] certBytes;
            try
            {
                certBytes = await SsoCertFetchClient.GetByteArrayAsync(fetchUri, cts.Token);
            }
            catch (Exception e)
            {
                await WriteJsonErrorAsync(HttpStatusCode.BadGateway, $"Failed to fetch certificate from '{url}': {e.Message}");
                return;
            }

            try
            {
                using X509Certificate2 _ = CertificateLoaderUtil.CreateCertificate(certBytes);
            }
            catch (Exception e)
            {
                await WriteJsonErrorAsync(HttpStatusCode.UnprocessableEntity, $"The content at '{url}' is not a valid certificate: {e.Message}");
                return;
            }

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                await using AsyncBlittableJsonTextWriter writer = new AsyncBlittableJsonTextWriter(ctx, ResponseBodyStream());
                ctx.Write(writer, new Sparrow.Json.Parsing.DynamicJsonValue { ["Base64"] = Convert.ToBase64String(certBytes) });
            }
        }

        private async Task WriteJsonErrorAsync(HttpStatusCode status, string error)
        {
            HttpContext.Response.StatusCode = (int)status;
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                await using AsyncBlittableJsonTextWriter writer = new AsyncBlittableJsonTextWriter(ctx, ResponseBodyStream());
                ctx.Write(writer, new Sparrow.Json.Parsing.DynamicJsonValue { ["Error"] = error });
            }
        }

        private string FormatPermissions(CertificateDefinition certificate)
        {
            return certificate?.Permissions != null
                ? Environment.NewLine + string.Join(Environment.NewLine, certificate.Permissions.Select(kvp => kvp.Key + ": " + kvp.Value.ToString()))
                : string.Empty;
            ;
        }

        public static async Task PutCertificateCollectionInCluster(CertificateDefinition certDef, byte[] certBytes, string password, ServerStore serverStore,
            TransactionOperationContext ctx, string twoFactorAuthenticationKey, string raftRequestId)
        {
            var collection = new X509Certificate2Collection();

            if (string.IsNullOrEmpty(password))
                CertificateLoaderUtil.Import(collection, certBytes);
            else
                CertificateLoaderUtil.Import(collection, certBytes, password, CertificateLoaderUtil.FlagsForPersist);

            var first = true;
            var collectionPrimaryKey = string.Empty;

            // we don't want to import items up the chain (signing keys)
            var issuers = new HashSet<string>();

            foreach (var x509Certificate in collection)
            {
                if (serverStore.Server.Certificate.ServerCertificate?.Thumbprint != null && serverStore.Server.Certificate.ServerCertificate.Thumbprint.Equals(x509Certificate.Thumbprint))
                    throw new InvalidOperationException($"You are trying to import the same server certificate ({x509Certificate.Thumbprint}) as the one which is already loaded. This is not supported.");

                if (x509Certificate.Issuer != x509Certificate.GetDisplayName())
                    issuers.Add(x509Certificate.Issuer);
            }

            foreach (var x509Certificate in collection)
            {
                if (issuers.Contains(x509Certificate.GetDisplayName()))
                    continue;

                var currentCertDef = new CertificateDefinition
                {
                    Name = certDef.Name,
                    Permissions = certDef.Permissions,
                    SecurityClearance = certDef.SecurityClearance,
                    Password = certDef.Password,
                    Usage = certDef.Usage ?? CertificateUsage.Client,
                };

                if (x509Certificate.HasPrivateKey)
                {
                    // avoid storing the private key
                    currentCertDef.Certificate = Convert.ToBase64String(x509Certificate.Export(X509ContentType.Cert));
                }

                // In case of a collection, we group all the certificates together and treat them as one unit.
                // They all have the same name and permissions but a different thumbprint.
                // The first certificate in the collection will be the primary certificate and its thumbprint will be the one shown in a GET request
                // The other certificates are secondary certificates and will contain a link to the primary certificate.
                currentCertDef.Thumbprint = x509Certificate.Thumbprint;
                currentCertDef.PublicKeyPinningHash = x509Certificate.GetPublicKeyPinningHash();
                currentCertDef.NotAfter = x509Certificate.NotAfter;
                currentCertDef.NotBefore = x509Certificate.NotBefore;
                currentCertDef.Certificate = Convert.ToBase64String(x509Certificate.Export(X509ContentType.Cert));

                if (first)
                {
                    var firstKey = x509Certificate.Thumbprint;
                    collectionPrimaryKey = firstKey;

                    foreach (var cert in collection)
                    {
                        if (issuers.Contains(cert.Subject))
                            continue;

                        if (cert.Thumbprint != firstKey)
                            currentCertDef.CollectionSecondaryKeys.Add(cert.Thumbprint);
                    }
                }
                else
                    currentCertDef.CollectionPrimaryKey = collectionPrimaryKey;

                var certKey = currentCertDef.Thumbprint;
                if (serverStore.CurrentRachisState == RachisState.Passive)
                {
                    if (twoFactorAuthenticationKey != null)
                    {
                        throw new InvalidOperationException("Cannot define two factor auth key when the node is in passive mode");
                    }
                    using (var certificate = ctx.ReadObject(currentCertDef.ToJson(), "Client/Certificate/Definition"))
                    using (var tx = ctx.OpenWriteTransaction())
                    {
                        serverStore.Cluster.PutLocalState(ctx, certKey, certificate, currentCertDef);
                        tx.Commit();
                    }
                }
                else
                {
                    var putCertificateCommand = new PutCertificateCommand(certKey, currentCertDef, $"{raftRequestId}/{certKey}")
                    {
                        TwoFactorAuthenticationKey = twoFactorAuthenticationKey
                    };
                    var putResult = await serverStore.PutValueInClusterAsync(putCertificateCommand);
                    await serverStore.Cluster.WaitForIndexNotification(putResult.Index);
                }

                first = false;
            }
        }

        [RavenAction("/admin/certificates/purge", "DELETE", AuthorizationStatus.Operator)]
        public async Task PurgeExpired()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (context.OpenReadTransaction())
            {
                var allCerts = new Dictionary<string, BlittableJsonReaderObject>();

                GetAllRegisteredCertificates(context, allCerts, false);

                var keysToDelete = new List<string>();

                foreach (var cert in allCerts)
                {
                    if (cert.Value.TryGet(nameof(CertificateDefinition.NotAfter), out DateTime notAfter) && DateTime.UtcNow > notAfter)
                        keysToDelete.Add(cert.Key);
                }

                if (RavenLogManager.Instance.IsAuditEnabled)
                {
                    foreach (string keyToDelete in keysToDelete)
                    {
                        LogAuditForServer("DELETE", $"Certificate '{keyToDelete}'.");
                    }
                }

                await DeleteInternal(keysToDelete, GetRaftRequestIdFromQuery());
            }

            HttpContext.Response.StatusCode = (int)HttpStatusCode.NoContent;
        }

        [RavenAction("/admin/certificates", "DELETE", AuthorizationStatus.Operator)]
        public async Task Delete()
        {
            var thumbprint = GetQueryStringValueAndAssertIfSingleAndNotEmpty("thumbprint");

            var feature = HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection;
            var clientCert = feature?.Certificate;

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (ctx.OpenReadTransaction())
            {
                if (clientCert?.Thumbprint != null && clientCert.Thumbprint.Equals(thumbprint))
                {
                    var clientCertDef = ReadCertificateFromCluster(ctx, thumbprint);
                    throw new InvalidOperationException($"Cannot delete {clientCertDef?.Name} because it's the current client certificate being used");
                }

                var definition = ReadCertificateFromCluster(ctx, thumbprint);
                if (definition != null && (definition.SecurityClearance == SecurityClearance.ClusterAdmin || definition.SecurityClearance == SecurityClearance.ClusterNode)
                    && IsClusterAdmin() == false)
                {
                    var clientCertDef = ReadCertificateFromCluster(ctx, clientCert?.Thumbprint);
                    throw new InvalidOperationException(
                        $"Cannot delete the certificate '{definition.Name}' with '{definition.SecurityClearance}' security clearance because the current client certificate being used has a lower clearance: {clientCertDef.SecurityClearance}");
                }

                if (string.IsNullOrEmpty(definition?.CollectionPrimaryKey) == false)
                    throw new InvalidOperationException(
                        $"Cannot delete the certificate '{definition.Name}' with thumbprint '{definition.Thumbprint}'. You need to delete the primary certificate of the collection: {definition.CollectionPrimaryKey}");

                var keysToDelete = new List<string>
                {
                    thumbprint
                };

                if (definition != null)
                    keysToDelete.AddRange(definition.CollectionSecondaryKeys);

                if (AuditLogger.IsAuditEnabled)
                {
                    LogAuditForServer("DELETE", $"Certificate '{thumbprint}'.");
                }

                await DeleteInternal(keysToDelete, GetRaftRequestIdFromQuery());
            }

            HttpContext.Response.StatusCode = (int)HttpStatusCode.NoContent;
        }

        private CertificateDefinition ReadCertificateFromCluster(TransactionOperationContext ctx, string key)
        {
            var certificate = ServerStore.Cluster.GetCertificateByThumbprint(ctx, key);
            if (certificate == null)
                return null;

            return JsonDeserializationServer.CertificateDefinition(certificate);
        }

        private async Task DeleteInternal(List<string> keys, string requestId)
        {
            // Delete from cluster
            var res = await ServerStore.SendToLeaderAsync(new DeleteCertificateCollectionFromClusterCommand(requestId)
            {
                Names = keys
            });
            await ServerStore.Cluster.WaitForIndexNotification(res.Index);

            // Delete from local state
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                using (var tx = ctx.OpenWriteTransaction())
                {
                    ServerStore.Cluster.DeleteLocalState(ctx, keys);
                    tx.Commit();
                }
            }
        }

        [RavenAction("/admin/certificates", "GET", AuthorizationStatus.Operator)]
        public async Task GetCertificates()
        {
            var thumbprint = GetStringQueryString("thumbprint", required: false);
            var name = GetStringQueryString("name", required: false);
            var metadataOnly = GetBoolValueQueryString("metadataOnly", required: false) ?? false;
            var includeSecondary = GetBoolValueQueryString("secondary", required: false) ?? false;

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (context.OpenReadTransaction())
            {
                var certificateList = new Dictionary<string, BlittableJsonReaderObject>(StringComparer.OrdinalIgnoreCase);

                try
                {
                    if (string.IsNullOrEmpty(thumbprint))
                    {
                        const string serverCertificateName = "Server Certificate";
                        // The server cert is not part of the local state or the cluster certificates, we add it to the list separately
                        if ((name == null || name == serverCertificateName) && Server.Certificate.ServerCertificate != null)
                        {
                            var serverCertDef = new CertificateDefinition
                            {
                                Name = serverCertificateName,
                                Certificate = Convert.ToBase64String(Server.Certificate.ServerCertificate.Export(X509ContentType.Cert)),
                                Permissions = new Dictionary<string, DatabaseAccess>(),
                                SecurityClearance = SecurityClearance.ClusterNode,
                                Thumbprint = Server.Certificate.ServerCertificate.Thumbprint,
                                PublicKeyPinningHash = Server.Certificate.ServerCertificate.GetPublicKeyPinningHash(),
                                NotAfter = Server.Certificate.ServerCertificate.NotAfter,
                                NotBefore = Server.Certificate.ServerCertificate.NotBefore,
                                Usage = CertificateUsage.RavenServer
                            };

                            var serverCert = context.ReadObject(serverCertDef.ToJson(metadataOnly), "Server/Certificate/Definition");

                            certificateList.TryAdd(Server.Certificate.ServerCertificate?.Thumbprint, serverCert);

                            var certificateForCommunication = Server.Certificate.ClientCertificate;
                            if (IsClientCertificateDifferentFromServerCertificate())
                            {
                                var serverCertForCommunicationDef = new CertificateDefinition
                                {
                                    Name = "Server Certificate for communication " + ServerStore.NodeTag,
                                    Certificate = Convert.ToBase64String(certificateForCommunication.Export(X509ContentType.Cert)),
                                    Permissions = new Dictionary<string, DatabaseAccess>(),
                                    SecurityClearance = SecurityClearance.ClusterNode,
                                    Thumbprint = certificateForCommunication.Thumbprint,
                                    PublicKeyPinningHash = certificateForCommunication.GetPublicKeyPinningHash(),
                                    NotAfter = certificateForCommunication.NotAfter,
                                    NotBefore = certificateForCommunication.NotBefore,
                                    Usage = CertificateUsage.RavenServerForCommunication
                                };

                                var serverCertForCommunication = context.ReadObject(serverCertForCommunicationDef.ToJson(metadataOnly),
                                    "ServerClient/Certificate/Definition");

                                certificateList.TryAdd(certificateForCommunication.Thumbprint, serverCertForCommunication);
                            }
                        }

                        GetAllRegisteredCertificates(context, certificateList, includeSecondary, name, metadataOnly);
                    }
                    else
                    {
                        if (TryGetAndAddCertificateByThumbprint(context, certificateList, thumbprint, metadataOnly) == false)
                        {
                            HttpContext.Response.StatusCode = (int)HttpStatusCode.NotFound;
                            return;
                        }
                    }

                    var wellKnown = ServerStore.Configuration.Security.WellKnownAdminCertificates;

                    await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
                    {
                        writer.WriteStartObject();
                        writer.WriteArray(context, "Results", certificateList.ToArray(), (w, c, cert) => c.Write(w, cert.Value));
                        writer.WriteComma();
                        writer.WritePropertyName("LoadedServerCert");
                        writer.WriteString(Server.Certificate.ServerCertificate?.Thumbprint);
                        writer.WriteComma();

                        if (IsClientCertificateDifferentFromServerCertificate())
                        {
                            writer.WritePropertyName("LoadedServerCertForCommunication");
                            writer.WriteString(Server.Certificate.ClientCertificate?.Thumbprint);
                            writer.WriteComma();
                        }

                        writer.WriteArray("WellKnownAdminCerts", wellKnown);
                        writer.WriteComma();
                        writer.WriteArray("WellKnownIssuers", Server.WellKnownIssuers?.Select(x => x.Thumbprint) ?? Array.Empty<string>());
                        writer.WriteEndObject();
                    }
                }
                finally
                {
                    foreach (var cert in certificateList)
                        cert.Value?.Dispose();
                }
            }
        }

        private bool TryGetCertificateByThumbprint(TransactionOperationContext context, string thumbprint, out BlittableJsonReaderObject certificate)
        {
            certificate = ServerStore.CurrentRachisState == RachisState.Passive
                ? ServerStore.Cluster.GetLocalStateByThumbprint(context, thumbprint)
                : ServerStore.Cluster.GetCertificateByThumbprint(context, thumbprint);
            return certificate != null;
        }

        private bool TryGetAndAddCertificateByThumbprint(TransactionOperationContext context, Dictionary<string, BlittableJsonReaderObject> certificateList,
            string thumbprint, bool metadataOnly)
        {
            if (TryGetCertificateByThumbprint(context, thumbprint, out var certificate) == false)
                return false;

            var definition = JsonDeserializationServer.CertificateDefinition(certificate);
            if (string.IsNullOrEmpty(definition.CollectionPrimaryKey) == false)
            {
                certificate.Dispose();
                if (TryGetCertificateByThumbprint(context, definition.CollectionPrimaryKey, out certificate) == false)
                    return false;
            }

            if (metadataOnly)
            {
                certificate.Dispose();
                certificate = context.ReadObject(definition.ToJson(true), "Client/Certificate/Definition");
            }

            certificateList.TryAdd(thumbprint, certificate);
            return true;
        }

        private void GetAllRegisteredCertificates(
            TransactionOperationContext context,
            Dictionary<string, BlittableJsonReaderObject> certificates,
            bool includeSecondary,
            string name = null,
            bool metadataOnly = false)
        {
            var localCertificates = ServerStore.CurrentRachisState == RachisState.Passive
                // If we are passive, we take the certs from the local state
                ? ClusterStateMachine.GetAllCertificatesFromLocalState(context)
                : ClusterStateMachine.GetAllCertificatesFromCluster(context, GetStart(), GetPageSize());

            foreach (var (thumbprint, certificate) in localCertificates)
            {
                var def = JsonDeserializationServer.CertificateDefinition(certificate);
                if (name != null && name != def.Name || includeSecondary == false && string.IsNullOrEmpty(def.CollectionPrimaryKey) == false)
                {
                    certificate.Dispose();
                    continue;
                }

                if (def.NotBefore == null && def.Certificate != null)
                {
                    // NotBefore will be null if the certificate was generated prior to adding the NotBefore property to class CertificateMetadata
                    // So we are manually extracting this info - See issue RavenDB-18519
                    var tempCertificate = CertificateLoaderUtil.CreateCertificate(Convert.FromBase64String(def.Certificate));
                    using (tempCertificate)
                    {
                        def.NotBefore = tempCertificate.NotBefore;
                    }

                }

                var certificateRef = certificate;
                if (metadataOnly)
                {
                    var defJson = def.ToJson(true);

                    if (HttpContext.Request.IsFromStudio())
                    {
                        var hasTwoFactor = certificate.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out string _);

                        defJson[HasTwoFactorFieldName] = hasTwoFactor;
                    }

                    certificateRef = context.ReadObject(defJson, "Client/Certificate/Definition");

                    certificate.Dispose();
                }
                else
                {
                    // make sure we don't leak fields like TwoFactorAuthenticationKey
                    certificateRef = context.ReadObject(def.ToJson(false), "Client/Certificate/Definition");
                }

                certificates.TryAdd(thumbprint, certificateRef);
            }
        }

        private BlittableJsonReaderObject TryBuildSsoCertificateDefinitionForWhoAmI(TransactionOperationContext ctx, X509Certificate2 clientCert)
        {
            RavenServer.AuthenticateConnection auth = HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection;
            if (auth?.IsSsoAuthenticated != true)
                return null;

            X509Extension ssoUserIdExtension = clientCert.Extensions[Constants.Certificates.SsoUserIdExtensionOid];
            if (ssoUserIdExtension == null)
                return null;

            SsoExtensionPayload payload = CertificateUtils.DecodeSsoUserIdExtension(ssoUserIdExtension.RawData);
            if (payload.IsEmpty)
                return null;

            CertificateDefinition storedEntry = ServerStore.Cluster.GetSsoClientCertificateByIdentity(ctx, payload);
            if (storedEntry == null)
                return null;

            CertificateDefinition ssoUserDef = new CertificateDefinition
            {
                Name = storedEntry.Name,
                Permissions = storedEntry.Permissions ?? new Dictionary<string, DatabaseAccess>(),
                SecurityClearance = storedEntry.SecurityClearance,
                Thumbprint = clientCert.Thumbprint,
                Usage = CertificateUsage.SsoClient,
                SsoServerPublicKeyPinningHashes = storedEntry.SsoServerPublicKeyPinningHashes ?? new List<string>(),
                AllowAnySsoServer = storedEntry.AllowAnySsoServer,
                SsoIdentifiers = storedEntry.SsoIdentifiers ?? new List<SsoIdentifier>(),
                Disabled = storedEntry.Disabled,
                NotAfter = clientCert.NotAfter,
                NotBefore = clientCert.NotBefore
            };
            return ctx.ReadObject(ssoUserDef.ToJson(), "SSO/Certificate/Definition");
        }

        [RavenAction("/certificates/whoami", "GET", AuthorizationStatus.UnauthenticatedClients)]
        public async Task WhoAmI()
        {
            var clientCert = GetCurrentCertificate();

            if (clientCert == null)
            {
                NoContentStatus();
                return;
            }

            clientCert = RavenServer.GetCertificateForAuthorization(clientCert);

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (ctx.OpenReadTransaction())
            {
                var certificate = ServerStore.Cluster.GetCertificateByThumbprint(ctx, clientCert.Thumbprint) ??
                                  ServerStore.Cluster.GetLocalStateByThumbprint(ctx, clientCert.Thumbprint);

                if (certificate == null)
                {
                    certificate = TryBuildSsoCertificateDefinitionForWhoAmI(ctx, clientCert);

                    // Let's check if the client is using the server certificate or one of the well known admin certs.
                    var wellKnown = ServerStore.Configuration.Security.WellKnownAdminCertificates;

                    if (certificate == null && Server.IsServerCertificate(clientCert))
                    {
                        if (Server.Certificate.ServerCertificate != null)
                        {
                            var serverCertDef = new CertificateDefinition
                            {
                                Name = "Server Certificate",
                                Certificate = Convert.ToBase64String(Server.Certificate.ServerCertificate.Export(X509ContentType.Cert)),
                                Permissions = new Dictionary<string, DatabaseAccess>(),
                                SecurityClearance = SecurityClearance.ClusterNode,
                                Thumbprint = Server.Certificate.ServerCertificate.Thumbprint,
                                PublicKeyPinningHash = Server.Certificate.ServerCertificate.GetPublicKeyPinningHash(),
                                NotAfter = Server.Certificate.ServerCertificate.NotAfter,
                                NotBefore = Server.Certificate.ServerCertificate.NotBefore,
                                Usage = CertificateUsage.RavenServer
                            };

                            certificate = ctx.ReadObject(serverCertDef.ToJson(), "Server/Certificate/Definition");
                        }

                        if (IsClientCertificateDifferentFromServerCertificate())
                        {
                            var serverClientCertDef = new CertificateDefinition
                            {
                                Name = "Server Certificate For Communication " + ServerStore.NodeTag,
                                Certificate = Convert.ToBase64String(Server.Certificate.ClientCertificate.Export(X509ContentType.Cert)),
                                Permissions = new Dictionary<string, DatabaseAccess>(),
                                SecurityClearance = SecurityClearance.ClusterNode,
                                Thumbprint = Server.Certificate.ClientCertificate.Thumbprint,
                                PublicKeyPinningHash = Server.Certificate.ClientCertificate.GetPublicKeyPinningHash(),
                                NotAfter = Server.Certificate.ClientCertificate.NotAfter,
                                NotBefore = Server.Certificate.ClientCertificate.NotBefore,
                                Usage = CertificateUsage.RavenServerForCommunication
                            };

                            certificate = ctx.ReadObject(serverClientCertDef.ToJson(), "ServerClient/Certificate/Definition");
                        }
                    }
                    else if (certificate == null && wellKnown != null && wellKnown.Contains(clientCert.Thumbprint, StringComparer.OrdinalIgnoreCase))
                    {
                        var wellKnownCertDef = new CertificateDefinition
                        {
                            Name = "Well Known Admin Certificate",
                            Permissions = new Dictionary<string, DatabaseAccess>(),
                            SecurityClearance = SecurityClearance.ClusterAdmin,
                            Thumbprint = clientCert.Thumbprint,
                            PublicKeyPinningHash = clientCert.GetPublicKeyPinningHash(),
                            Usage = CertificateUsage.Client
                        };
                        certificate = ctx.ReadObject(wellKnownCertDef.ToJson(), "WellKnown/Certificate/Definition");
                    }
                    else if (certificate == null && Server.CertificateHasWellKnownIssuer(clientCert, out var issuer))
                    {
                        var wellKnownCertDef = new CertificateDefinition
                        {
                            Name = "Well Known Issuer Certificate: " + issuer,
                            Permissions = new Dictionary<string, DatabaseAccess>(),
                            SecurityClearance = SecurityClearance.ClusterAdmin,
                            Thumbprint = clientCert.Thumbprint,
                            PublicKeyPinningHash = clientCert.GetPublicKeyPinningHash(),
                            Usage = CertificateUsage.WellKnownIssuer
                        };
                        certificate = ctx.ReadObject(wellKnownCertDef.ToJson(), "WellKnown/Certificate/Definition");
                    }
                    else if (certificate == null)
                    {
                        NoContentStatus();
                        return;
                    }
                }

                await using (var writer = new AsyncBlittableJsonTextWriter(ctx, ResponseBodyStream()))
                {
                    var certificateDefinition = JsonDeserializationServer.CertificateDefinition(certificate);
                    var certificateDJV = certificateDefinition.ToJson(false);

                    var hasTwoFactor = certificate.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out string _);
                    certificateDJV[HasTwoFactorFieldName] = hasTwoFactor;

                    var feature = HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection;
                    certificateDJV[TwoFactorExpirationDate] = feature?.TwoFactorAuthRegistration?.Expiry;

                    ctx.Write(writer, certificateDJV);
                }
            }
        }

        private bool IsClientCertificateDifferentFromServerCertificate()
        {
            return Server.Certificate.ClientCertificate != null && Server.Certificate.ClientCertificate.Thumbprint != Server.Certificate.ServerCertificate?.Thumbprint;
        }

        [RavenAction("/admin/certificates/edit", "POST", AuthorizationStatus.Operator)]
        public async Task Edit()
        {
            await ServerStore.EnsureNotPassiveAsync();

            var deleteTwoFactorConfiguration = GetBoolValueQueryString("deleteTwoFactorConfiguration", required: false) ?? false;

            var feature = HttpContext.Features.Get<IHttpAuthenticationFeature>() as RavenServer.AuthenticateConnection;
            var clientCert = feature?.Certificate;

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            using (var certificateJson = await ctx.ReadForDiskAsync(RequestBodyStream(), "edit-certificate"))
            {
                var editedCertificate = JsonDeserializationServer.CertificateDefinition(certificateJson);
                
                certificateJson.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out string newTwoFactorAuthenticationKey);
                var disabledExplicitlySet = certificateJson.TryGet(nameof(CertificateMetadata.Disabled), out bool disabledValue);
                
                var ssoHashesExplicitlySet = certificateJson.TryGet(nameof(CertificateMetadata.SsoServerPublicKeyPinningHashes), out BlittableJsonReaderArray _);
                var allowAnySsoExplicitlySet = certificateJson.TryGet(nameof(CertificateMetadata.AllowAnySsoServer), out bool _);
                var ssoIdentifiersExplicitlySet = certificateJson.TryGet(nameof(CertificateMetadata.SsoIdentifiers), out BlittableJsonReaderArray _);

                ValidateCertificateDefinition(editedCertificate, ServerStore);

                CertificateDefinition existingCertificate;
                string twoFactorAuthenticationKey;
                bool effectiveDisabled = false;
                using (ctx.OpenWriteTransaction())
                {
                    var existingCertificateJson = ServerStore.Cluster.GetCertificateByThumbprint(ctx, editedCertificate.Thumbprint);
                    if (existingCertificateJson == null)
                        throw new InvalidOperationException($"Cannot edit permissions for certificate with thumbprint '{editedCertificate.Thumbprint}'. It doesn't exist in the cluster.");
                    
                    existingCertificateJson.TryGet(nameof(PutCertificateCommand.TwoFactorAuthenticationKey), out twoFactorAuthenticationKey);

                    if (deleteTwoFactorConfiguration)
                    {
                        twoFactorAuthenticationKey = null;
                    }
                    else if (string.IsNullOrEmpty(newTwoFactorAuthenticationKey) == false)
                    {
                        twoFactorAuthenticationKey = newTwoFactorAuthenticationKey;
                    }

                    existingCertificate = JsonDeserializationServer.CertificateDefinition(existingCertificateJson);

                    effectiveDisabled = disabledExplicitlySet ? disabledValue : existingCertificate.Disabled;

                    if (effectiveDisabled)
                    {
                        if (existingCertificate.SecurityClearance == SecurityClearance.ClusterNode)
                            throw new InvalidOperationException($"Cannot disable the certificate '{existingCertificate.Name}'. It is a cluster node certificate and disabling it would break the cluster.");

                        if (Server.Certificate.ServerCertificate?.Thumbprint != null &&
                            existingCertificate.Thumbprint == Server.Certificate.ServerCertificate.Thumbprint)
                            throw new InvalidOperationException($"Cannot disable the server certificate '{existingCertificate.Name}'.");

                        if (clientCert?.Thumbprint != null && clientCert.Thumbprint == existingCertificate.Thumbprint)
                            throw new InvalidOperationException($"Cannot disable the certificate '{existingCertificate.Name}' because it is currently being used for this request.");
                    }

                    if (existingCertificate.Usage == CertificateUsage.SsoServer)
                        throw new InvalidOperationException($"Cannot edit SSO server certificate '{existingCertificate.Name}'. SSO server certificates are not editable.");

                    if ((existingCertificate.SecurityClearance == SecurityClearance.ClusterAdmin || existingCertificate.SecurityClearance == SecurityClearance.ClusterNode) && IsClusterAdmin() == false)
                    {
                        var clientCertDef = ReadCertificateFromCluster(ctx, clientCert?.Thumbprint);
                        throw new InvalidOperationException($"Cannot edit the certificate '{existingCertificate.Name}'. It has '{existingCertificate.SecurityClearance}' security clearance while the current client certificate being used has a lower clearance: {clientCertDef.SecurityClearance}");
                    }

                    if ((editedCertificate.SecurityClearance == SecurityClearance.ClusterAdmin || editedCertificate.SecurityClearance == SecurityClearance.ClusterNode) && IsClusterAdmin() == false)
                    {
                        var clientCertDef = ReadCertificateFromCluster(ctx, clientCert?.Thumbprint);
                        throw new InvalidOperationException($"Cannot edit security clearance to '{editedCertificate.SecurityClearance}' for certificate '{existingCertificate.Name}'. Only a 'Cluster Admin' can do that and your current client certificate has a lower clearance: {clientCertDef.SecurityClearance}");
                    }

                    ServerStore.Cluster.DeleteLocalState(ctx, editedCertificate.Thumbprint);
                }

                bool isSsoClient = existingCertificate.Usage == CertificateUsage.SsoClient;
                List<string> mergedSsoHashes = existingCertificate.SsoServerPublicKeyPinningHashes;
                bool mergedAllowAnySso = existingCertificate.AllowAnySsoServer;
                List<SsoIdentifier> mergedSsoIdentifiers = existingCertificate.SsoIdentifiers;

                if (isSsoClient)
                {
                    // SSO edits fully replace the stored definition: a field that is present in the request wins,
                    // even when it is an empty list (which clears it). A field that is absent from the request is
                    // left untouched, so partial edits (e.g. just toggling Disabled) never wipe the SSO config.
                    if (ssoHashesExplicitlySet)
                        mergedSsoHashes = editedCertificate.SsoServerPublicKeyPinningHashes;
                    if (allowAnySsoExplicitlySet)
                        mergedAllowAnySso = editedCertificate.AllowAnySsoServer;
                    if (ssoIdentifiersExplicitlySet)
                        mergedSsoIdentifiers = editedCertificate.SsoIdentifiers;
                }

                if (isSsoClient && mergedSsoIdentifiers != null)
                {
                    // Enforce SSO identity uniqueness on edit, mirroring PutSsoUser. Exclude the entry being
                    // edited by thumbprint so keeping an entry's own identifier is allowed.
                    using (ctx.OpenReadTransaction())
                    {
                        foreach (var id in mergedSsoIdentifiers)
                        {
                            var payload = new SsoExtensionPayload(id.Identifier, id.Provider, id.Domain);
                            var existing = ServerStore.Cluster.GetSsoClientCertificateByIdentity(ctx, payload);
                            if (existing != null && string.Equals(existing.Thumbprint, editedCertificate.Thumbprint, StringComparison.OrdinalIgnoreCase) == false)
                            {
                                throw new InvalidOperationException(
                                    $"An SSO user entry with identity '{payload.GetDisplayIdentity()}' already exists " +
                                    $"(name: '{existing.Name}'). Each SSO identity can belong to only one entry.");
                            }
                        }
                    }
                }

                if (RavenLogManager.Instance.IsAuditEnabled)
                {
                    var permissions = FormatPermissions(editedCertificate);

                    var ssoAuditInfo = string.Empty;
                    if (isSsoClient)
                    {
                        var serverHashes = mergedAllowAnySso
                            ? "any"
                            : string.Join(", ", (mergedSsoHashes ?? new List<string>()).Select(h => $"'{h}'"));
                        var identifiers = string.Join(", ", (mergedSsoIdentifiers ?? new List<SsoIdentifier>())
                            .Select(id => new SsoExtensionPayload(id.Identifier, id.Provider, id.Domain).GetDisplayIdentity()));
                        ssoAuditInfo = $" Identifiers: [{identifiers}]. SsoServerHashes: [{serverHashes}]. AllowAnySsoServer: {mergedAllowAnySso}.";
                    }

                    LogAuditForServer("CHANGE",
                        $"Certificate {editedCertificate?.Name}. Security Clearance: {editedCertificate?.SecurityClearance}. Permissions: {permissions}. TwoFactor: {string.IsNullOrEmpty(twoFactorAuthenticationKey) == false}. Disabled: {effectiveDisabled}.{ssoAuditInfo}");
                }

                PutCertificateCommand cmd = new PutCertificateCommand(editedCertificate.Thumbprint,
                    new CertificateDefinition
                    {
                        Name = editedCertificate.Name,
                        Certificate = existingCertificate.Certificate,
                        Permissions = editedCertificate.Permissions,
                        SecurityClearance = editedCertificate.SecurityClearance,
                        Thumbprint = existingCertificate.Thumbprint,
                        PublicKeyPinningHash = existingCertificate.PublicKeyPinningHash,
                        NotAfter = existingCertificate.NotAfter,
                        NotBefore = existingCertificate.NotBefore,
                        Disabled = effectiveDisabled,
                        Usage = existingCertificate.Usage ?? CertificateUsage.Client,
                        SsoServerPublicKeyPinningHashes = mergedSsoHashes,
                        AllowAnySsoServer = mergedAllowAnySso,
                        SsoIdentifiers = mergedSsoIdentifiers
                    }, GetRaftRequestIdFromQuery())
                { TwoFactorAuthenticationKey = twoFactorAuthenticationKey };

                var putResult = await ServerStore.PutValueInClusterAsync(cmd);
                await ServerStore.Cluster.WaitForIndexNotification(putResult.Index);

                NoContentStatus(HttpStatusCode.Created);
            }
        }

        [RavenAction("/admin/certificates/export", "GET", AuthorizationStatus.Operator)]
        public async Task GetClusterCertificates()
        {
            if (Server.Certificate.ServerCertificate == null)
                return;

            var collection = new X509Certificate2Collection();
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            {
                // exporting server cert probably because of ETL or Replication so client cert is needed
                CertificateLoaderUtil.Import(collection, Server.Certificate.ServerCertificate.Export(X509ContentType.Cert));

                if (ServerStore.CurrentRachisState != RachisState.Passive)
                {
                    using (context.OpenReadTransaction())
                    {
                        List<(string ItemName, BlittableJsonReaderObject Value)> allItems = null;
                        try
                        {
                            allItems = ClusterStateMachine.GetAllCertificatesFromCluster(context, 0, long.MaxValue).ToList();
                            var clusterNodes = allItems.Select(item => JsonDeserializationServer.CertificateDefinition(item.Value))
                                .Where(certificateDef => certificateDef.SecurityClearance == SecurityClearance.ClusterNode)
                                .ToList();

                            foreach (var cert in clusterNodes)
                            {
                                var x509Certificate2 = CertificateLoaderUtil.CreateCertificate(Convert.FromBase64String(cert.Certificate));

                                if (collection.Contains(x509Certificate2) == false)
                                    CertificateLoaderUtil.Import(collection, x509Certificate2.Export(X509ContentType.Cert));
                            }
                        }
                        finally
                        {
                            if (allItems != null)
                            {
                                foreach (var cert in allItems)
                                    cert.Value?.Dispose();
                            }
                        }
                    }
                }
            }

            var pfx = collection.Export(X509ContentType.Pfx);

            var contentDisposition = "attachment; filename=ServerCertificatesCollection.pfx";
            HttpContext.Response.Headers[Constants.Headers.ContentDisposition] = contentDisposition;
            HttpContext.Response.ContentType = "application/octet-stream";

            await HttpContext.Response.Body.WriteAsync(pfx, 0, pfx.Length);
        }
        
        [RavenAction("/admin/certificates/for-communication/export", "GET", AuthorizationStatus.Operator)]
        public async Task GetServerCertificateForCommunication()
        {
            if (Server.Certificate.ClientCertificate == null)
                return;

            var bytes = Server.Certificate.ClientCertificate.Export(X509ContentType.Cert);

            var contentDisposition = "attachment; filename=ServerCertificateForCommunication.crt";
            HttpContext.Response.Headers["Content-Disposition"] = contentDisposition;
            HttpContext.Response.ContentType = "application/octet-stream";

            await HttpContext.Response.Body.WriteAsync(bytes, 0, bytes.Length);
        }

        [RavenAction("/admin/certificates/mode", "GET", AuthorizationStatus.ClusterAdmin)]
        public async Task Mode()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                await using (var writer = new AsyncBlittableJsonTextWriter(ctx, ResponseBodyStream()))
                {
                    writer.WriteStartObject();
                    writer.WritePropertyName("SetupMode");
                    writer.WriteString(ServerStore.Configuration.Core.SetupMode.ToString());
                    writer.WriteEndObject();
                }
            }
        }

        [RavenAction("/admin/certificates/cluster-domains", "GET", AuthorizationStatus.ClusterAdmin)]
        public async Task ClusterDomains()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (context.OpenReadTransaction())
            {
                List<string> domains = null;
                if (ServerStore.CurrentRachisState != RachisState.Passive)
                {
                    ClusterTopology clusterTopology;
                    clusterTopology = ServerStore.GetClusterTopology(context);
                    domains = clusterTopology.AllNodes.Select(node => new Uri(node.Value).DnsSafeHost).ToList();
                }
                else
                {
                    var myUrl = Server.Configuration.Core.PublicServerUrl.HasValue
                        ? Server.Configuration.Core.PublicServerUrl.Value.UriValue
                        : Server.Configuration.Core.ServerUrls[0];
                    var myDomain = new Uri(myUrl).DnsSafeHost;
                    domains = new List<string>
                    {
                        myDomain
                    };
                }

                await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
                {
                    writer.WriteStartObject();
                    writer.WritePropertyName("ClusterDomains");

                    writer.WriteStartArray();
                    var first = true;
                    foreach (var domain in domains)
                    {
                        if (first == false)
                            writer.WriteComma();
                        first = false;
                        writer.WriteString(domain);
                    }
                    writer.WriteEndArray();

                    writer.WriteEndObject();
                }
            }
        }

        [RavenAction("/admin/certificates/replacement/reset", "POST", AuthorizationStatus.ClusterAdmin)]
        public Task ReplacementReset()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (var tx = context.OpenWriteTransaction())
            {
                ClusterStateMachine.DeleteItem(context, CertificateReplacement.CertificateReplacementDoc);
                tx.Commit();
            }

            return NoContent();
        }

        [RavenAction("/admin/certificates/replacement/status", "GET", AuthorizationStatus.ClusterAdmin)]
        public async Task ReplacementStatus()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
            {
                using (context.OpenReadTransaction())
                {
                    var certStatus = ServerStore.Cluster.GetItem(context, CertificateReplacement.CertificateReplacementDoc);

                    if (certStatus != null)
                    {
                        certStatus.TryGet(nameof(CertificateReplacement.Confirmations), out int confirmations);
                        certStatus.TryGet(nameof(CertificateReplacement.Thumbprint), out string thumbprint);
                        certStatus.TryGet(nameof(CertificateReplacement.OldThumbprint), out string oldThumbprint);
                        certStatus.TryGet(nameof(CertificateReplacement.ReplaceImmediately), out bool replaceImmediately);
                        certStatus.TryGet(nameof(CertificateReplacement.Replaced), out int replaced);

                        // Not writing the certificate itself, because it has the private key
                        writer.WriteStartObject();
                        writer.WritePropertyName(nameof(CertificateReplacement.Confirmations));
                        writer.WriteInteger(confirmations);
                        writer.WriteComma();
                        writer.WritePropertyName(nameof(CertificateReplacement.Thumbprint));
                        writer.WriteString(thumbprint);
                        writer.WriteComma();
                        writer.WritePropertyName(nameof(CertificateReplacement.OldThumbprint));
                        writer.WriteString(oldThumbprint);
                        writer.WriteComma();
                        writer.WritePropertyName(nameof(CertificateReplacement.ReplaceImmediately));
                        writer.WriteBool(replaceImmediately);
                        writer.WriteComma();
                        writer.WritePropertyName(nameof(CertificateReplacement.Replaced));
                        writer.WriteInteger(replaced);
                        writer.WriteEndObject();
                    }
                    else
                    {
                        HttpContext.Response.StatusCode = (int)HttpStatusCode.NotFound;
                    }
                }
            }
        }

        [RavenAction("/admin/certificates/letsencrypt/renewal-date", "GET", AuthorizationStatus.ClusterAdmin)]
        public async Task RenewalDate()
        {
            if (ServerStore.Configuration.Core.SetupMode != SetupMode.LetsEncrypt)
                throw new InvalidOperationException("This server wasn't set up using the Let's Encrypt setup mode.");

            if (Server.Certificate.ServerCertificate == null)
                throw new InvalidOperationException("The server certificate is not loaded.");

            var (_, renewalDate) = Server.CalculateRenewalDate(Server.Certificate, false);

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
            {
                writer.WriteStartObject();
                writer.WritePropertyName("EstimatedRenewal");
                writer.WriteDateTime(renewalDate, true);
                writer.WriteEndObject();
            }
        }

        [RavenAction("/admin/certificates/letsencrypt/force-renew", "POST", AuthorizationStatus.ClusterAdmin, CorsMode = CorsMode.Cluster)]
        public async Task ForceRenew()
        {
            if (ServerStore.IsLeader())
            {
                if (ServerStore.Configuration.Core.SetupMode != SetupMode.LetsEncrypt)
                    throw new InvalidOperationException("Cannot force renew for this server certificate. This server wasn't set up using the Let's Encrypt setup mode.");

                if (Server.Certificate.ServerCertificate == null)
                    throw new InvalidOperationException("Cannot force renew this Let's Encrypt server certificate. The server certificate is not loaded.");

                if (RavenLogManager.Instance.IsAuditEnabled)
                {
                    LogAuditForServer("RENEW", "Server certificate");
                }

                try
                {
                    var success = Server.RefreshClusterCertificate(true, GetRaftRequestIdFromQuery());
                    using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
                    await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
                    {
                        writer.WriteStartObject();
                        writer.WritePropertyName(nameof(ForceRenewResult.Success));
                        writer.WriteBool(success);
                        writer.WriteEndObject();
                    }

                    return;
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException($"Failed to force renew the Let's Encrypt server certificate for domain: {Server.Certificate.ServerCertificate.GetNameInfo(X509NameType.SimpleName, false)}", e);
                }
            }

            RedirectToLeader();
        }

        [RavenAction("/admin/certificates/refresh", "POST", AuthorizationStatus.ClusterAdmin, CorsMode = CorsMode.Cluster)]
        public Task TriggerCertificateRefresh()
        {
            if (ServerStore.IsLeader() || ServerStore.Configuration.Core.SetupMode != SetupMode.LetsEncrypt)
            {
                // What we do here is trigger the refresh cycle which normally happens once an hour.

                // The difference between this and /admin/certificates/letsencrypt/force-renew is that here we also allow it for non-LetsEncrypt setups
                // in which case we'll check if the certificate changed on disk (or via executable) and if so we'll update it immediately on the local node (only)

                var replaceImmediately = GetBoolValueQueryString("replaceImmediately", required: false) ?? false;

                if (Server.Certificate.ServerCertificate == null)
                    throw new InvalidOperationException("Failed to trigger a certificate refresh cycle. The server certificate is not loaded.");

                try
                {
                    Server.RefreshClusterCertificate(replaceImmediately, GetRaftRequestIdFromQuery());
                }
                catch (Exception e)
                {
                    throw new InvalidOperationException("Failed to trigger a certificate refresh cycle", e);
                }

                return NoContent();
            }
            RedirectToLeader();
            return Task.CompletedTask;
        }

        [RavenAction("/admin/certificates/replace-cluster-cert", "POST", AuthorizationStatus.ClusterAdmin, CorsMode = CorsMode.Cluster)]
        public async Task ReplaceClusterCert()
        {
            if (ServerStore.IsLeader())
            {
                var replaceImmediately = GetBoolValueQueryString("replaceImmediately", required: false) ?? false;

                await ServerStore.EnsureNotPassiveAsync();
                using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
                using (var certificateJson = await ctx.ReadForDiskAsync(RequestBodyStream(), "replace-cluster-cert"))
                {
                    try
                    {
                        var certificate = JsonDeserializationServer.CertificateDefinition(certificateJson);

                        if (string.IsNullOrWhiteSpace(certificate.Certificate))
                            throw new ArgumentException($"{nameof(certificate.Certificate)} is a required field in the certificate definition.");

                        var certBytes = Convert.FromBase64String(certificate.Certificate);

                        // Load the password protected certificate and export it without a password, to send it through the cluster.
                        if (string.IsNullOrWhiteSpace(certificate.Password) == false)
                        {
                            try
                            {
                                var cert = new X509Certificate2Collection();
                                CertificateLoaderUtil.Import(cert, certBytes, certificate.Password, CertificateLoaderUtil.FlagsForExport);
                                // Exporting with the private key, but without the password
                                certBytes = cert.Export(X509ContentType.Pkcs12);
                                certificate.Certificate = Convert.ToBase64String(certBytes);
                                certificate.Password = null;
                            }
                            catch (Exception e)
                            {
                                throw new ArgumentException("Failed to load the password protected certificate and export it back. Is the password correct?", e);
                            }
                        }

                        // Ensure we'll be able to load the certificate
                        X509Certificate2 newCertificate;
                        try
                        {
                            var flags = CertificateLoaderUtil.FlagsForPersist;
    
                            // macOS Keychain rigidly blocks exports of persisted private keys.
                            // Keeping the key in memory (Ephemeral) by dropping PersistKeySet bypasses this.
                            if (PlatformDetails.RunningOnMacOsx)
                            {
                                flags = CertificateLoaderUtil.FlagsForExport; 
                            }

                            newCertificate = CertificateLoaderUtil.CreateCertificate(certBytes, flags: flags);
                        }
                        catch (Exception e)
                        {
                            throw new ArgumentException("Unable to load the provided certificate.", e);
                        }

                        if (IsClusterAdmin() == false)
                            throw new InvalidOperationException("Cannot replace the server certificate. Only a ClusterAdmin can do this.");

                        var timeoutTask = TimeoutManager.WaitFor(TimeSpan.FromSeconds(60), ServerStore.ServerShutdown);
                        if (Logger.IsDebugEnabled)
                        {
                            Logger.Debug("Initiating the replacement of the certificate upon explicit request - '/admin/certificates/replace-cluster-cert'.");
                        }
                        var replicationTask = Server.StartCertificateReplicationAsync(newCertificate, certificate.Password, replaceImmediately, GetRaftRequestIdFromQuery());

                        await Task.WhenAny(replicationTask, timeoutTask);
                        if (replicationTask.IsCompleted == false)
                            throw new TimeoutException("Timeout when trying to replace the server certificate.");

                        await replicationTask;
                    }
                    catch (Exception e)
                    {
                        throw new InvalidOperationException("Failed to replace the server certificate.", e);
                    }
                }

                NoContentStatus(HttpStatusCode.Created);
                return;
            }

            RedirectToLeader();
        }

        [RavenAction("/admin/certificates/local-state", "GET", AuthorizationStatus.Operator)]
        public async Task GetLocalState()
        {
            var includeSecondary = GetBoolValueQueryString("secondary", required: false) ?? false;

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext context))
            using (context.OpenReadTransaction())
            {
                var certificateList = new Dictionary<string, BlittableJsonReaderObject>();

                try
                {
                    var localCertKeys = ServerStore.Cluster.GetCertificateThumbprintsFromLocalState(context).ToList();

                    foreach (var localCertKey in localCertKeys)
                    {
                        var localCertificate = ServerStore.Cluster.GetLocalStateByThumbprint(context, localCertKey);
                        if (localCertificate == null)
                            continue;

                        var def = JsonDeserializationServer.CertificateDefinition(localCertificate);

                        if (includeSecondary || string.IsNullOrEmpty(def.CollectionPrimaryKey))
                            certificateList.TryAdd(localCertKey, localCertificate);
                        else
                            localCertificate.Dispose();
                    }

                    await using (var writer = new AsyncBlittableJsonTextWriter(context, ResponseBodyStream()))
                    {
                        writer.WriteStartObject();
                        writer.WriteArray(context, "Results", certificateList.ToArray(), (w, c, cert) => c.Write(w, cert.Value));
                        writer.WriteEndObject();
                    }
                }
                finally
                {
                    foreach (var cert in certificateList)
                        cert.Value?.Dispose();
                }
            }
        }

        [RavenAction("/admin/certificates/local-state", "DELETE", AuthorizationStatus.ClusterAdmin)]
        public Task LocalStateDelete()
        {
            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                List<string> localStateKeys;
                using (ctx.OpenReadTransaction())
                {
                    localStateKeys = ServerStore.Cluster.GetCertificateThumbprintsFromLocalState(ctx).ToList();
                }

                // Delete from local state
                using (var tx = ctx.OpenWriteTransaction())
                {
                    ServerStore.Cluster.DeleteLocalState(ctx, localStateKeys);
                    tx.Commit();
                }
            }

            return NoContent();
        }

        [RavenAction("/admin/certificates/local-state/apply", "POST", AuthorizationStatus.ClusterAdmin)]
        public async Task LocalStateApply()
        {
            if (ServerStore.CurrentRachisState == RachisState.Passive)
                throw new AuthorizationException("RavenDB is in passive state. Cannot apply certificates to the cluster.");

            var raftRequestId = GetRaftRequestIdFromQuery();

            using (ServerStore.ContextPool.AllocateOperationContext(out TransactionOperationContext ctx))
            {
                long? index = null;
                List<string> localStateKeys;
                using (ctx.OpenReadTransaction())
                {
                    localStateKeys = ServerStore.Cluster.GetCertificateThumbprintsFromLocalState(ctx).ToList();
                    foreach (var localStateKey in localStateKeys)
                    {
                        // if there are trusted certificates in the local state, we will register them in the cluster now
                        using (var localCertificate = ServerStore.Cluster.GetLocalStateByThumbprint(ctx, localStateKey))
                        {
                            var certificateDefinition = JsonDeserializationServer.CertificateDefinition(localCertificate);

                            // In the beginning of 4.0 we had the server certificate stored together with all the other certs (in the local state and in the cluster).
                            // If it's the case now, we make sure not to transfer it to the cluster.
                            if (certificateDefinition.Thumbprint == ServerStore.Server.Certificate.ServerCertificate.Thumbprint)
                                continue;

                            var (newIndex, _) = await ServerStore.PutValueInClusterAsync(new PutCertificateCommand(localStateKey, certificateDefinition, $"{raftRequestId}/{localStateKey}"));
                            index = newIndex;
                        }
                    }
                }

                if (index.HasValue)
                    await ServerStore.Cluster.WaitForIndexNotification(index.Value);

                // Delete from local state
                using (var tx = ctx.OpenWriteTransaction())
                {
                    ServerStore.Cluster.DeleteLocalState(ctx, localStateKeys);
                    tx.Commit();
                }
            }

            NoContentStatus();
        }

        public static void ValidateCertificateDefinition(CertificateDefinition certificate, ServerStore serverStore)
        {
            if (string.IsNullOrWhiteSpace(certificate.Name))
                throw new ArgumentException($"{nameof(certificate.Name)} is a required field in the certificate definition");

            if (certificate.NotAfter.HasValue && certificate.NotAfter <= DateTime.UtcNow.Date)
                throw new ArgumentException("The certificate expiration date must be in the future.");

            ValidatePermissions(certificate, serverStore);

            serverStore.LicenseManager.AssertCanAddReadOnlyCertificates(certificate);
        }

        private static void ValidatePermissions(CertificateDefinition certificate, ServerStore serverStore)
        {
            if (certificate.Permissions == null)
                throw new ArgumentException($"{nameof(certificate.Permissions)} is a required field in the certificate definition");

            foreach (var kvp in certificate.Permissions)
            {
                if (string.IsNullOrWhiteSpace(kvp.Key))
                    throw new ArgumentException("Error in permissions in the certificate definition, database name is empty");

                if (ResourceNameValidator.IsValidResourceName(kvp.Key, serverStore.Configuration.Core.DataDirectory.FullPath, out var errorMessage) == false)
                    throw new ArgumentException("Error in permissions in the certificate definition:" + errorMessage);

                switch (kvp.Value)
                {
                    case DatabaseAccess.ReadWrite:
                    case DatabaseAccess.Admin:
                    case DatabaseAccess.Read:
                        break;

                    default:
                        throw new ArgumentException($"Error in permissions in the certificate definition, invalid access {kvp.Value} for database {kvp.Key}");
                }
            }
        }

    }
}
