import type { ReactNode } from "react";
import { useFormContext, useWatch } from "react-hook-form";
import { RefreshCw, SparklesIcon } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/shadcn/ui/alert";
import { Button } from "@/components/shadcn/ui/button";
import { InputGroupAddon } from "@/components/shadcn/ui/input-group";
import { FormInput } from "@/components/form/form-input";
import { FormTextarea } from "@/components/form/form-textarea";
import {
    toAgentIdentifier,
    type AgentFormData,
} from "@/pages/setup/add-capability-wizard/capability-wizard-validation";
import { AgentActionsSection } from "@/pages/setup/add-capability-wizard/steps/review/agent-actions-section";
import { AgentParametersSection } from "@/pages/setup/add-capability-wizard/steps/review/agent-parameters-section";
import { AgentQueryToolsSection } from "@/pages/setup/add-capability-wizard/steps/review/agent-query-tools-section";
import { SectionHeader } from "@/components/section-header";

export const SYSTEM_PROMPT_PLACEHOLDER =
    "Describe the agent's purpose and capabilities. " +
    "E.g.: You are a customer support assistant for an e-commerce platform, " +
    "capable of answering questions about products and orders.";

type AgentConfigurationTabProps = {
    hasEditedIdentifier: boolean;
    setHasEditedIdentifier: (hasEdited: boolean) => void;
};

export function AgentConfigurationTab({ hasEditedIdentifier, setHasEditedIdentifier }: AgentConfigurationTabProps) {
    const { control, getValues, setValue } = useFormContext<AgentFormData>();
    const mode = useWatch({ control, name: "create.mode" });
    // The AI-made configuration is seeded into the same editable fields as a manual one, so this
    // notice is the only cue that edits diverge from what the AI produced.
    const isAiMade = mode === "ai" || mode === "prompt";

    function setIdentifierFromName(name: string) {
        setValue("review.identifier", toAgentIdentifier(name), { shouldValidate: true });
    }

    return (
        <div className="grid gap-4">
            {isAiMade && (
                <Alert>
                    <SparklesIcon />
                    <AlertTitle>AI-made configuration</AlertTitle>
                    <AlertDescription>
                        This configuration was generated by AI. Any changes you make here override the AI-made setup.
                    </AlertDescription>
                </Alert>
            )}
            <div className="grid gap-8">
                <ConfigurationSection
                    title="Configure basic settings"
                    description="Define your agent's purpose and its AI provider connection."
                >
                    <div className="grid gap-5 rounded-lg border bg-background p-4">
                        <FormInput
                            control={control}
                            name="review.name"
                            label="Agent name"
                            placeholder="e.g. Customer Service Agent"
                            afterChange={(event) => {
                                if (!hasEditedIdentifier) {
                                    setIdentifierFromName(event.target.value);
                                }
                            }}
                        />
                        <FormInput
                            control={control}
                            name="review.identifier"
                            label="Identifier"
                            placeholder="e.g. customer-service-agent"
                            description="A unique identifier for the agent. Permanent once the agent is created."
                            // The identifier follows the agent name until the operator types their own.
                            afterChange={() => setHasEditedIdentifier(true)}
                            addons={
                                <InputGroupAddon align="inline-end">
                                    <Button
                                        type="button"
                                        variant="ghost"
                                        onClick={() => {
                                            setIdentifierFromName(getValues("review.name"));
                                            setHasEditedIdentifier(false);
                                        }}
                                    >
                                        <RefreshCw />
                                        Regenerate
                                    </Button>
                                </InputGroupAddon>
                            }
                        />
                        <FormTextarea
                            control={control}
                            name="review.systemPrompt"
                            label="System prompt"
                            placeholder={SYSTEM_PROMPT_PLACEHOLDER}
                            rows={7}
                            description="Defines the agent's role and capabilities, guiding the LLM's responses throughout the conversation."
                        />
                    </div>
                </ConfigurationSection>

                <ConfigurationSection
                    title="Set agent parameters"
                    description="Define query parameters that the agent will replace with fixed values before executing a query tool against the database."
                >
                    <AgentParametersSection />
                </ConfigurationSection>

                <ConfigurationSection
                    title="Define agent tools"
                    description="Tools are a controlled way to pass context to the LLM."
                >
                    <AgentQueryToolsSection />
                </ConfigurationSection>

                <ConfigurationSection
                    title="Define agent actions"
                    description="Actions let the agent call an external webhook during a conversation and use its response."
                >
                    <AgentActionsSection />
                </ConfigurationSection>
            </div>
        </div>
    );
}

function ConfigurationSection({
    title,
    description,
    children,
}: {
    title: string;
    description: string;
    children: ReactNode;
}) {
    return (
        <section className="grid gap-3">
            <SectionHeader level="section" title={title} description={description} />
            {children}
        </section>
    );
}
