#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Raven.Tests.MonoForAndroid.Resource", IsApplication=true)]

namespace Raven.Tests.MonoForAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int DeselectAllButton = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int FailedTests = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int FailedTestsList = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int PassedTests = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int PassedTestsList = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int RunTests = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int SelectAllButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int TestsList = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int TestsStatus = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int checkBox1 = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int myButton = 2131034123;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Testing = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TestItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TestSelection = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int RunTests = 2130968578;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
