namespace Raven.Studio.Features.JsonEditor {
    using ActiproSoftware.Text;
    using System;
    
    
    /// <summary>
    /// Represents a example text provider for the <c>Json</c> language.
    /// </summary>
    /// <remarks>
    /// This type was generated by the Actipro Language Designer tool v12.1.561.0 (http://www.actiprosoftware.com).
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LanguageDesigner", "12.1.561.0")]
    public partial class JsonExampleTextProvider : Object, IExampleTextProvider {
        
        /// <summary>
        /// Gets the example text, a code snippet of the related language.
        /// </summary>
        /// <value>The example text, a code snippet of the related language.</value>
        public String ExampleText {
            get {
                return "{\r\n  \"Property\": \"StringValue\",\r\n  \"Another Property\": [],\r\n  \"Third Property\": [" +
                    "\r\n  \t{ \"Nested\" : 0 },\r\n\t{ \"2nd Nested\" : true\r\n  ],\r\n  \"Fourth\" : false\r\n}";
            }
        }
    }
}
