.git/
.vs/
.idea/
bench/
test/
docs/
artifacts/
scripts/


**/bin/
**/obj/
**/node_modules/
**/*.user
**/*.suo

src/Raven.Quill.Web/dist/
src/Raven.Quill.Web/storybook-static/

**/.env
**/.env.local
**/appsettings.Development.json
**/appsettings.Local.json

src/Raven.Pal/osxcross/
src/Raven.Pal/*.sdk.tar.xz
