//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raven.Management.Client.Silverlight.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseUrl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseUrl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raven.Management.Client.Silverlight.Common.DatabaseUrl", typeof(DatabaseUrl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/static/{1}?.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/static?.
        /// </summary>
        public static string AttachmentGetAll {
            get {
                return ResourceManager.GetString("AttachmentGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/bulk_docs?.
        /// </summary>
        public static string DocumentBatch {
            get {
                return ResourceManager.GetString("DocumentBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/docs/{1}?.
        /// </summary>
        public static string DocumentGet {
            get {
                return ResourceManager.GetString("DocumentGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/docs?.
        /// </summary>
        public static string DocumentGetAll {
            get {
                return ResourceManager.GetString("DocumentGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/queries?.
        /// </summary>
        public static string DocumentGetMany {
            get {
                return ResourceManager.GetString("DocumentGetMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/docs?.
        /// </summary>
        public static string DocumentPost {
            get {
                return ResourceManager.GetString("DocumentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/docs/{1}?.
        /// </summary>
        public static string DocumentPut {
            get {
                return ResourceManager.GetString("DocumentPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/indexes/{1}?definition=yes&amp;.
        /// </summary>
        public static string IndexGet {
            get {
                return ResourceManager.GetString("IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/indexes?.
        /// </summary>
        public static string IndexGetAll {
            get {
                return ResourceManager.GetString("IndexGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/indexes?.
        /// </summary>
        public static string IndexGetMany {
            get {
                return ResourceManager.GetString("IndexGetMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/indexes/{1}?.
        /// </summary>
        public static string IndexPut {
            get {
                return ResourceManager.GetString("IndexPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/stats?.
        /// </summary>
        public static string StatisticsGet {
            get {
                return ResourceManager.GetString("StatisticsGet", resourceCulture);
            }
        }
    }
}
