using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Raven.Analyzers.Generators;
using Raven.Analyzers.Shared;

namespace Raven.Analyzers
{
    /// <summary>
    /// Records the shape of every index class declared in the compilation as assembly-level
    /// <c>RavenIndexMetadataAttribute</c> entries, so the analyzers can read it back from any assembly.
    /// </summary>
    /// <remarks>
    /// An index's shape lives in a constructor body, which does not survive into compiled metadata; an
    /// attribute does. Running here — in the assembly that declares the index, where the source is
    /// available — is what lets an analyzer in a different assembly reason about that index at all, and
    /// it makes a command-line build and an IDE agree, since both read the same recorded values instead
    /// of one reading source and the other reading nothing.
    /// <para>
    /// Abstract bases are recorded too: a derived index in another assembly needs its base's facts to
    /// know whether the chain assigns a Map.
    /// </para>
    /// </remarks>
    [Generator(LanguageNames.CSharp)]
    public sealed class IndexMetadataGenerator : IIncrementalGenerator
    {
        private const string GeneratedFileName = "RavenIndexMetadata.g.cs";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<INamedTypeSymbol?> indexClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) =>
                    {
                        var declaration = (ClassDeclarationSyntax)ctx.Node;
                        return ctx.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol symbol
                               && SyntaxHelpers.IsIndexCreationTask(symbol)
                            ? symbol
                            : null;
                    })
                .Where(static symbol => symbol is not null);

            // Collect() so the whole set is emitted as one file with one attribute per index. Partial
            // classes yield the same symbol more than once, hence the de-duplication in Emit.
            IncrementalValueProvider<(Compilation Left, ImmutableArray<INamedTypeSymbol?> Right)> source =
                context.CompilationProvider.Combine(indexClasses.Collect());

            context.RegisterSourceOutput(source, static (spc, pair) => Emit(spc, pair.Left, pair.Right));
        }

        private static void Emit(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<INamedTypeSymbol?> indexClasses)
        {
            if (indexClasses.IsDefaultOrEmpty)
                return;

            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Index shapes recorded for the RavenDB analyzers. Do not edit.");
            builder.AppendLine();

            foreach (INamedTypeSymbol? indexClass in indexClasses)
            {
                if (indexClass == null || !seen.Add(indexClass))
                    continue;

                // An index nested in a generic type, or generic itself, cannot be named by a plain
                // typeof() in every case; skip rather than emit source that will not compile.
                if (!TryGetTypeOfExpression(indexClass, out string typeOfArgument))
                    continue;

                IndexMetadata metadata = IndexShapeAggregator.Compute(indexClass, compilation);
                AppendAttribute(builder, typeOfArgument, metadata);
            }

            context.AddSource(GeneratedFileName, SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private static void AppendAttribute(StringBuilder builder, string typeOfArgument, IndexMetadata metadata)
        {
            builder.Append("[assembly: global::")
                   .Append(KnownTypes.RavenIndexMetadataAttributeFullName)
                   .Append("(typeof(")
                   .Append(typeOfArgument)
                   .Append(')');

            // Unanalyzable indexes are recorded explicitly rather than omitted, so a consumer can tell
            // "the generator looked and could not read this" from "nothing recorded this index at all".
            // Both bail, but only the former is a statement about the index.
            builder.Append(", Analyzable = ").Append(metadata.Analyzable ? "true" : "false");

            if (metadata.Analyzable)
            {
                AppendStringArray(builder, nameof(IndexMetadata.MapFields), metadata.MapFields);
                AppendStringArray(builder, nameof(IndexMetadata.StoredFields), metadata.StoredFields);
                builder.Append(", StoreAllFields = ").Append(metadata.StoreAllFields ? "true" : "false");
                builder.Append(", AssignsMap = ").Append(metadata.AssignsMap ? "true" : "false");
                builder.Append(", AddMapCount = ").Append(metadata.AddMapCount);
                builder.Append(", AddMapInLoop = ").Append(metadata.AddMapInLoop ? "true" : "false");
                builder.Append(", UsesAdditionalCode = ").Append(metadata.UsesAdditionalCode ? "true" : "false");
            }

            builder.AppendLine(")]");
        }

        private static void AppendStringArray(StringBuilder builder, string name, ImmutableHashSet<string> values)
        {
            if (values.IsEmpty)
                return;

            builder.Append(", ").Append(name).Append(" = new string[] { ");

            // Ordered so the generated file is stable across runs: an unordered set would reshuffle it
            // and defeat the incremental caching that keeps IDE typing responsive.
            bool first = true;
            foreach (string value in values.OrderBy(v => v, System.StringComparer.Ordinal))
            {
                if (!first)
                    builder.Append(", ");

                builder.Append('"').Append(value.Replace("\\", "\\\\").Replace("\"", "\\\"")).Append('"');
                first = false;
            }

            builder.Append(" }");
        }

        /// <summary>
        /// Builds the argument for a <c>typeof(...)</c> naming <paramref name="type"/>, or returns false
        /// when the type cannot be named that way.
        /// </summary>
        private static bool TryGetTypeOfExpression(INamedTypeSymbol type, out string expression)
        {
            expression = string.Empty;

            // A type parameter anywhere in the containing chain cannot appear in an assembly-level
            // typeof(), and an unbound generic index is not something a query can target concretely.
            if (type.IsGenericType || type.ContainingType?.IsGenericType == true)
                return false;

            if (type.DeclaredAccessibility == Accessibility.Private
                || type.DeclaredAccessibility == Accessibility.Protected)
            {
                // Not nameable from an assembly-level attribute.
                return false;
            }

            expression = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return true;
        }
    }
}
