using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Raven.Analyzers.Shared;

namespace Raven.Analyzers.Generators
{
    /// <summary>
    /// Emits one assembly-level <c>RavenIndexMetadataAttribute</c> per index class in the compilation,
    /// recording the fields it maps and stores and how it defines itself.
    /// </summary>
    /// <remarks>
    /// An index declares its shape in a constructor body. Constructor bodies are not part of compiled
    /// metadata, so an analyzer looking at a query has no way to inspect an index that came from a
    /// referenced assembly. Attributes are part of metadata, so recording the shape here, where the
    /// source is still available, is what makes those indexes analyzable at all. It also keeps a
    /// command-line build and an IDE in agreement, because both read these values rather than one
    /// reading source and the other reading nothing.
    /// <para>
    /// Abstract bases get an entry too. A derived index in another assembly needs its base's facts to
    /// tell whether the chain assigns a Map.
    /// </para>
    /// </remarks>
    [Generator(LanguageNames.CSharp)]
    public sealed class IndexMetadataGenerator : IIncrementalGenerator
    {
        private const string GeneratedFileName = "RavenIndexMetadata.g.cs";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<INamedTypeSymbol?> indexClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) =>
                    {
                        var declaration = (ClassDeclarationSyntax)ctx.Node;
                        return ctx.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol symbol
                               && SyntaxHelpers.IsIndexCreationTask(symbol)
                            ? symbol
                            : null;
                    })
                .Where(static symbol => symbol is not null);

            // Collect() so the whole set lands in one file with one attribute per index. A partial class
            // yields the same symbol once per part, which is what the de-duplication in Emit is for.
            IncrementalValueProvider<(Compilation Left, ImmutableArray<INamedTypeSymbol?> Right)> source =
                context.CompilationProvider.Combine(indexClasses.Collect());

            context.RegisterSourceOutput(source, static (spc, pair) => Emit(spc, pair.Left, pair.Right));
        }

        private static void Emit(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<INamedTypeSymbol?> indexClasses)
        {
            if (indexClasses.IsDefaultOrEmpty)
                return;

            IndexMetadataRegistry metadataRegistry = new();
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("// Index shapes recorded for the RavenDB analyzers. Do not edit.");
            builder.AppendLine();

            foreach (INamedTypeSymbol? indexClass in indexClasses)
            {
                if (indexClass == null || !seen.Add(indexClass))
                    continue;

                // Some index classes cannot be named by an assembly-level typeof() at all. Skip those
                // rather than emit source that will not compile.
                if (!TryGetTypeOfExpression(indexClass, out string typeOfArgument))
                    continue;

                IndexMetadata metadata = IndexShapeAggregator.Compute(indexClass, compilation, metadataRegistry);
                AppendAttribute(builder, typeOfArgument, metadata);
            }

            context.AddSource(GeneratedFileName, SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private static void AppendAttribute(StringBuilder builder, string typeOfArgument, IndexMetadata metadata)
        {
            builder.Append("[assembly: global::")
                   .Append(KnownTypes.RavenIndexMetadataAttributeFullName)
                   .Append("(typeof(")
                   .Append(typeOfArgument)
                   .Append(')');

            // Unreadable indexes get an entry saying so rather than no entry at all. Both make a consumer
            // bail, but only an explicit false says the index was looked at and could not be read, which
            // is worth being able to tell apart when something is not reporting and you want to know why.
            builder.Append(", Analyzable = ").Append(metadata.Analyzable ? "true" : "false");

            if (metadata.Analyzable)
            {
                AppendStringArray(builder, nameof(IndexMetadata.MapFields), metadata.MapFields);
                AppendStringArray(builder, nameof(IndexMetadata.StoredFields), metadata.StoredFields);
                builder.Append(", StoreAllFields = ").Append(metadata.StoreAllFields ? "true" : "false");
                builder.Append(", AssignsMap = ").Append(metadata.AssignsMap ? "true" : "false");
                builder.Append(", AddMapCount = ").Append(metadata.AddMapCount);
                builder.Append(", AddMapInLoop = ").Append(metadata.AddMapInLoop ? "true" : "false");
                builder.Append(", UsesAdditionalCode = ").Append(metadata.UsesAdditionalCode ? "true" : "false");
            }

            builder.AppendLine(")]");
        }

        private static void AppendStringArray(StringBuilder builder, string name, ImmutableHashSet<string> values)
        {
            if (values.IsEmpty)
                return;

            builder.Append(", ").Append(name).Append(" = new string[] { ");

            // Sorted to keep the generated file byte-identical between runs. An unordered set would
            // reshuffle it and defeat the incremental caching that keeps typing responsive in an IDE.
            bool first = true;
            foreach (string value in values.OrderBy(v => v, System.StringComparer.Ordinal))
            {
                if (!first)
                    builder.Append(", ");

                builder.Append('"').Append(value.Replace("\\", "\\\\").Replace("\"", "\\\"")).Append('"');
                first = false;
            }

            builder.Append(" }");
        }

        /// <summary>
        /// Builds the argument for a <c>typeof(...)</c> naming <paramref name="type"/>. Returns false when
        /// the type cannot be named from an assembly-level attribute.
        /// </summary>
        private static bool TryGetTypeOfExpression(INamedTypeSymbol type, out string expression)
        {
            expression = string.Empty;

            // A type parameter cannot appear in an assembly-level typeof(), and a query cannot target an
            // unbound generic index concretely anyway.
            if (type.IsGenericType || type.ContainingType?.IsGenericType == true)
                return false;

            if (type.DeclaredAccessibility == Accessibility.Private
                || type.DeclaredAccessibility == Accessibility.Protected)
            {
                return false;
            }

            expression = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return true;
        }
    }
}
