// Based on Jeff Wilcox' Syntax highlighter: http://www.jeff.wilcox.name/2010/03/syntax-highlighting-text-block/
// He really deservces most of the credits...

// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
// <auto-generated />
// No style analysis for imported project.

namespace Raven.Studio.Controls.JeffWilcox.SyntaxHighlighting
{
	using System.Collections.Generic;

	/// <summary>
	/// Defines how ColorCode will parse the source code of a given language.
	/// </summary>
	interface ILanguage
	{
		/// <summary>
		/// Gets the identifier of the language (e.g., csharp).
		/// </summary>
		string Id { get; }

		/// <summary>
		/// Gets the first line pattern (regex) to use when determining if the language matches a source text.
		/// </summary>
		string FirstLinePattern { get; }

		/// <summary>
		/// Gets the "friendly" name of the language (e.g., C#).
		/// </summary>
		string Name { get; }

		/// <summary>
		/// Gets the collection of language rules in the language.
		/// </summary>
		IList<LanguageRule> Rules { get; }
	}
}