using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Raven.Client.Documents.Operations.AI.Agents;

namespace Raven.Client.Documents.AI;

public interface IAiConversationOperations<out T> where T : new()
{
    /// <summary>
    /// The identifier of this conversation.
    /// </summary>
    string Id { get; }

    /// <summary>
    /// The most recent answer generated by the AI agent.
    /// </summary>
    T Answer { get; }

    /// <summary>
    /// The current RavenDB change vector for this conversation document,  
    /// used to detect concurrent modifications.
    /// </summary>
    string ChangeVector { get; }

    /// <summary>
    /// Retrieves the list of action-tool requests  
    /// that the AI agent needs you to execute.
    /// </summary>
    /// <returns>
    /// A sequence of <see cref="AiAgentActionRequest"/>  
    /// representing the tools the agent asked for.
    /// </returns>
    IEnumerable<AiAgentActionRequest> RequiredActions();

    /// <summary>
    /// Adds a string response for a given action request.
    /// </summary>
    /// <param name="actionId">
    /// The identifier of the action request.
    /// </param>
    /// <param name="actionResponse">
    /// The textual response to supply to the agent.
    /// </param>
    void AddActionResponse(string actionId, string actionResponse);

    /// <summary>
    /// Adds a typed response object for a given action request.
    /// </summary>
    /// <typeparam name="TResponse">
    /// The CLR type of the response object.  
    /// Must be a reference type.
    /// </typeparam>
    /// <param name="actionId">
    /// The identifier of the action request.
    /// </param>
    /// <param name="actionResponse">
    /// The response object to supply to the agent.
    /// </param>
    void AddActionResponse<TResponse>(string actionId, TResponse actionResponse) where TResponse : class;

    /// <summary>
    /// Asynchronously executes one “turn” of the conversation:  
    /// sends the current prompt, processes any required actions,  
    /// and awaits the agent’s reply.
    /// </summary>
    /// <param name="token">
    /// A <see cref="CancellationToken"/> used to cancel the operation.
    /// </param>
    /// <returns>
    /// A <see cref="Task{ConversationResult}"/> containing a <see cref="AiConversationResult"/>  
    /// indicating the outcome of the turn:
    /// <list type="bullet">
    /// <item><see cref="AiConversationResult.ActionRequired"/> if the agent requires further interaction (e.g., pending tool requests).</item>
    /// <item><see cref="AiConversationResult.Done"/> if the conversation has completed and a final answer is available.</item>
    /// </list>
    /// </returns>
    Task<AiConversationResult> RunAsync(CancellationToken token = default);

    /// <summary>
    /// Synchronously executes one turn of the conversation.
    /// </summary>
    /// <returns>
    /// A <see cref="AiConversationResult"/> indicating the outcome of the turn:
    /// <list type="bullet">
    /// <item><see cref="AiConversationResult.ActionRequired"/> if more interaction is needed (e.g., pending tool requests).</item>
    /// <item><see cref="AiConversationResult.Done"/> if the conversation has completed and a final answer is available.</item>
    /// </list>
    /// </returns>
    AiConversationResult Run();

    /// <summary>
    /// Sets the next user prompt to send to the AI agent.
    /// </summary>
    /// <param name="userPrompt">
    /// The text of the user’s message.
    /// </param>
    void SetUserPrompt(string userPrompt);
}
