import { SelectOption } from "components/common/select/Select";

const allCountries = [
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos Islands",
    "Colombia",
    "Comoros",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Curacao",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Great Britain",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "Northern Ireland",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of the Congo",
    "Reunion",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Vietnam",
    "Virgin Islands",
    "Wallis and Futuna Islands",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

const allJobTitles = [
    "CEO/Founder",
    "CTO/CIO",
    "Enterprise Architect",
    "Data Architect",
    "VP of Technology",
    "VP Engineering",
    "Team Leader (of IT Project / SW Development)",
    "SW Development Manager",
    "Application Architect",
    "DBA",
    "IT Directors / Managers",
    "Solution Architect",
    "Sales Professional",
    "Product Manager",
    "Analyst",
    "Software Engineer",
    "Marketer",
    "Student",
    "Other",
];

const allIndustries = [
    "E-Commerce & Retail",
    "Financial Services (Banking, Insurance, etc)",
    "Gaming",
    "Healthcare",
    "Transportation, Logistics and Supply Chain",
    "Food & Beverages",
    "Content Management System",
    "IoT & Smart Device",
    "Smart City & Mobility",
    "Advertising & Marketing",
    "Agriculture",
    "Software Development",
    "Other",
];

const allHowYouPlanToUseRavenDB = [
    "I want to develop my NoSQL skills",
    "I am looking for a database for a new project",
    "I want to see if it's a right fit for my organization",
    "I just want to see what it can do",
];

const howYouPlanToUseRavenDBOptions: SelectOption[] = allHowYouPlanToUseRavenDB.map((option) => ({
    label: option,
    value: option,
}));

const nodeTags = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
];

const allStudioEnvironments = ["Production", "Testing", "Development", "None"] as const;

const allStudioEnvironmentOptions: SelectOption[] = allStudioEnvironments.map((env) => ({
    label: env,
    value: env,
}));

const indexingEngineTypes = ["Lucene", "Corax"] as const;

const indexingEngineTypeOptions: SelectOption[] = indexingEngineTypes.map((type) => ({
    label: type,
    value: type,
}));

const SETUP_WIZARD_MOCK_LICENSE_KEYS_IDS: Partial<Record<Raven.Server.Commercial.LicenseType, string>> = {
    None: "None",
    Community: "53f54157-3862-47b6-9dbd-94d323687a90",
    Essential: "53f54157-3862-47b6-9dbd-94d323687a91",
    Enterprise: "53f54157-3862-47b6-9dbd-94d323687a92",
    Developer: "53f54157-3862-47b6-9dbd-94d323687a93",
    Professional: "53f54157-3862-47b6-9dbd-94d323687a94",
};

export const setupWizardGA4Prefixes = {
    eulaStep: "setupWizard-eulaStep",
    setupMethod: "setupWizard-setupMethod",
    usePackageStep: "setupWizard-usePackageStep",
    licenseKeyStep: "setupWizard-licenseKeyStep",
    domainStep: "setupWizard-domainStep",
    securityStep: "setupWizard-securityStep",
    selfSignedCertificateStep: "setupWizard-selfSignedCertificateStep",
    nodeAddressStep: "setupWizard-nodeAddressStep",
    additionalSettingsStep: "setupWizard-additionalSettingsStep",
    finalStep: "setupWizard-finalStep",
    navigation: "setupWizard-navigation",
} as const;

const AGPL_MAX_CLUSTER_SIZE = 1; // Default to 1 (AGPL license) if the license is not available

export const setupWizardConstants = {
    allCountries,
    allJobTitles,
    allIndustries,
    allHowYouPlanToUseRavenDB,
    howYouPlanToUseRavenDBOptions,
    nodeTags,
    allStudioEnvironments,
    allStudioEnvironmentOptions,
    indexingEngineTypes,
    indexingEngineTypeOptions,
    SETUP_WIZARD_MOCK_LICENSE_KEYS_IDS,
    AGPL_MAX_CLUSTER_SIZE,
};
