using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Tests.Infrastructure")]
[assembly: InternalsVisibleTo("FastTests")]
[assembly: InternalsVisibleTo("SlowTests")]
[assembly: InternalsVisibleTo("EmbeddedTests")]
[assembly: InternalsVisibleTo("StressTests")]
[assembly: InternalsVisibleTo("RachisTests")]
[assembly: InternalsVisibleTo("InterversionTests")]
[assembly: InternalsVisibleTo("TypingsGenerator")]
[assembly: InternalsVisibleTo("Voron.Recovery")]
[assembly: InternalsVisibleTo("rvn")]
[assembly: InternalsVisibleTo("Raven.TestDriver")]
[assembly: InternalsVisibleTo("Tryouts")]
[assembly: InternalsVisibleTo("LicenseTests")]
[assembly: InternalsVisibleTo("Subscriptions.Benchmark")]
