//-----------------------------------------------------------------------
// <copyright file="BatchResult.cs" company="Hibernating Rhinos LTD">
//     Copyright (c) Hibernating Rhinos LTD. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
using System;
using Newtonsoft.Json.Linq;

namespace Raven.Database
{
	/// <summary>
	/// The result of a single operation inside a batch
	/// </summary>
	public class BatchResult
	{
		/// <summary>
		/// Gets or sets the etag generated by the etag (if applicable)
		/// </summary>
		/// <value>The etag.</value>
		public Guid? Etag { get; set; }
		/// <summary>
		/// Gets or sets the method used for the operation (PUT,DELETE,PATCH).
		/// </summary>
		/// <value>The method.</value>
		public string Method { get; set; }
		/// <summary>
		/// Gets or sets the key of the document
		/// </summary>
		/// <value>The key.</value>
		public string Key { get; set; }
		/// <summary>
		/// Gets or sets the updated metadata.
		/// </summary>
		/// <value>The metadata.</value>
		public JObject Metadata { get; set; }
	}
}
