//-----------------------------------------------------------------------
// <copyright file="BatchResult.cs" company="Hibernating Rhinos LTD">
//     Copyright (c) Hibernating Rhinos LTD. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
using System;
using Raven.Json.Linq;

namespace Raven.Abstractions.Data
{
	/// <summary>
	/// The result of a single operation inside a batch
	/// </summary>
	public class BatchResult
	{
		/// <summary>
		/// Gets or sets the etag generated by the etag (if applicable)
		/// </summary>
		/// <value>The etag.</value>
		public Etag Etag { get; set; }
		/// <summary>
		/// Gets or sets the method used for the operation (PUT,DELETE,PATCH).
		/// </summary>
		/// <value>The method.</value>
		public string Method { get; set; }
		/// <summary>
		/// Gets or sets the key of the document
		/// </summary>
		/// <value>The key.</value>
		public string Key { get; set; }
		/// <summary>
		/// Gets or sets the updated metadata.
		/// </summary>
		/// <value>The metadata.</value>
		public RavenJObject Metadata { get; set; }
		/// <summary>
		/// Gets or sets the updated Additional Data.
		/// </summary>
		/// <value>The metadata.</value>
		public RavenJObject AdditionalData { get; set; }
		/// <summary>
		/// Gets or sets the result of a PATCH operation.
		/// </summary>
		/// <value>The PatchResult.</value>
		public PatchResult? PatchResult { get; set; }
		/// <summary>
		/// Gets or sets the result of a DELETE operation.
		/// </summary>
		/// <value>true if the document was deleted, false if it did not exist.</value>
		public bool? Deleted { get; set; }
	}
}