name: compile

on:
  pull_request:
  push:

jobs:
  compile:
    name: Compile Server & Studio
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup runner
        run: |
          echo "Disk usage BEFORE cleanup:"
          df -h
          sudo rm -rf /opt/hostedtoolcache || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          echo "Disk usage AFTER cleanup:"
          df -h
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore
        run: |
          git clean -xfd
          dotnet restore

      - name: Build Client
        run: |
          dotnet build ./src/Raven.Client/Raven.Client.csproj /p:GenerateDocumentationFile=true
          
      - name: Build Server
        run: |
          dotnet build
        
      - name: Clear NuGet Cache
        run: |
          dotnet nuget locals all --clear

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'src/Raven.Studio/.nvmrc'
          
      - name: Restore
        run: |
          npm ci
          npm run restore
        working-directory: src/Raven.Studio

      - name: Compile Studio
        run: |
          npm run compile
        working-directory: src/Raven.Studio

