name: tests/studio

on:
  push:
    branches:
        - v6.2

  pull_request:
    branches:
        - v6.2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version-file: 'src/Raven.Studio/.nvmrc'

    - name: Install dependencies
      run: dotnet restore

    - name: Build dotnet
      run: dotnet build

    - name: Install npm dependencies
      run: npm install
      working-directory: ./src/Raven.Studio
  
    - name: Restore Studio
      run: npm run restore
      working-directory: ./src/Raven.Studio

    - name: Compile Studio
      run: npm run compile
      working-directory: ./src/Raven.Studio

    - name: Test Studio (jest)
      run: npm run test
      working-directory: ./src/Raven.Studio
      
    - name: Install Playwright
      run: npx playwright install --with-deps
      working-directory: ./src/Raven.Studio
      
    - name: Build Storybook
      run: npm run build-storybook --quiet
      working-directory: ./src/Raven.Studio
      
    - name: Test Studio (storybook)
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"  
      working-directory: ./src/Raven.Studio
